### ISSUE TITLE
Synology package

### ISSUE THREAD

**Issue by neox387** [piejanssens/premiumizer#1]
Hey,

Just wondering if you could make the synology package :D

Would be nice if this would work from sonarr :)

**Comment by piejanssens** [comment]
I don't have any spare time to continue with this (at this moment) but a Syno pkg is certainly something I want to create for this.

**Comment by neox387** [comment]
If u have time could you add an option for a watchdir so it would work with blackhole.
So I can mess around & try to create the synology package

**Comment by piejanssens** [comment]
I'll have a look at that :wink: 
Have you been using Premiumizer a few times already? 
No issues with it so far?

**Comment by neox387** [comment]
Tested it, made a fork bumpt some libs, for flask-socketio it now requires python-socketio instead of gevent-sockiot, or eventlet but couldn't make it work i'm not a programmer xP

Everything seems to work, did not test nzbtomedia yet tough.
But yea with a watchdir I could put it into testing with blackhole feature, better yet integration like u said in readme but that's gotta be harder I guess + couchpotato etc needs to implement it then.

donno if it's usefull but this guy wrote an api:
https://github.com/ChristophAl/premiumize
