### ISSUE TITLE
Initial settings file incompatible

### ISSUE THREAD

**Issue by kungfoolfighting** [piejanssens/premiumizer#100]
When I start a completely new instance of premiumizer by simply downloading the git repo and starting it, the program stops with this message:

```
01-03 16:33:08: INFO : Running at /premiumizer
01-03 16:33:08: ERROR : Uncaught exception
Traceback (most recent call last):
  File "premiumizer.py", line 334, in <module>
    cfg = PremConfig()
  File "premiumizer.py", line 185, in __init__
    self.check_config()
  File "premiumizer.py", line 298, in check_config
    cat_dir = os.path.join(self.download_location, y)
AttributeError: PremConfig instance has no attribute 'download_location'

```
The settings entry in questions looks like this on my machine: 

`download_location =
`
This can obviously be prevented by using a settings file where the download directory is set, but it should work out of the box for initial configuration.

**Comment by neox387** [comment]
whoops, broke it on previous PR where I moved some lines =D
