### ISSUE TITLE
Aria2 event hooks

### ISSUE THREAD

**Issue by bjsjr** [piejanssens/premiumizer#105]
Any chance you could add supports for any of the event hooks available for aria2?  Specifically, I would love support for --on-download-complete.

Perhaps it could be an option on the settings page. If ticked, it will add:
```
--on-download-complete on-download-complete.sh
```
to the command line.  If not, you send the command line you're currently sending.

**Comment by bjsjr** [comment]
Sorry, I believe I misinterpreted how this is done.  I'm going to close this request.

**Comment by neox387** [comment]
Well something like a custom script after a task is completed could work I Guess if that's what u mean :D
