### ISSUE TITLE
Enhancement: request

### ISSUE THREAD

**Issue by buntin7419** [piejanssens/premiumizer#111]
I would like to see Real-debrid integration. It's a far cheaper alternative and I can't find any tool simillar to this for it.
Any chance of this in the future?

**Comment by neox387** [comment]
Real debrid is only for file hosters? It does not have nzb access or torrent caching like premiumize.me?

**Comment by buntin7419** [comment]
Sorry for the late response.
It does not have Nzb support but does have torrent cache for 14 days.

**Comment by neox387** [comment]
Well anything could be possible, but would be lot of work/testing... 

Never looked into real debrid realy.. Im satisfied with premiumize.me and there support... 

With discounts like black friday it's only around 50 euro a year..

**Comment by piejanssens** [comment]
This utility is and will stay Premiumizer specific.
