### ISSUE TITLE
No drag and drop for Magnet links

### ISSUE THREAD

**Issue by buntin7419** [piejanssens/premiumizer#116]
Issue: I can drag and drop .torrent files but cannot drag and drop Magnet links, only copy and paste them.

**Comment by neox387** [comment]
You mean drop a .magnet file ? I'll add it

**Comment by buntin7419** [comment]
That's probably the same thing; never used a .magnet file... but I mean hold the cursor on the magnet link in an open browser window; left click and drag the link to the magnet link in the Premiumizer box window.
Makes for an easier life.

**Comment by neox387** [comment]
No Idea about that xD, I would just copy paste the link? Donno how You drag a link xP

Anyway need piejanssens to merge xP

**Comment by neox387** [comment]
I'll Test what u mean when I have time. 

Sonarr uses  .magnet files it's just a text file with a magnet extension that contain the magnet link, it does this when it can't catch the .torrent file

**Comment by buntin7419** [comment]
I'm pretty sure it's the same thing, so should be fine after the merge.
Drag&Drop's just faster when manually downloading. it will be a good edition.

**Comment by neox387** [comment]
Alright got it working for next pr
