### ISSUE TITLE
Startup fails because of missing setting

### ISSUE THREAD

**Issue by cremor** [piejanssens/premiumizer#120]
After the latest update (#119) my Premiumizer doesn't start any more. This is the log output:

```
06-25 08:29:19: ERROR : Uncaught exception
Traceback (most recent call last):
  File "C:\Diverses\Premiumizer\Premiumizer\Premiumizer.py", line 347, in <module>
    cfg = PremConfig()
  File "C:\Diverses\Premiumizer\Premiumizer\Premiumizer.py", line 186, in __init__
    self.check_config()
  File "C:\Diverses\Premiumizer\Premiumizer\Premiumizer.py", line 208, in check_config
    self.remove_cloud_delay = prem_config.getint('downloads', 'remove_cloud_delay')
  File "C:\Diverses\Premiumizer\Python\lib\ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "C:\Diverses\Premiumizer\Python\lib\ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
  File "C:\Diverses\Premiumizer\Python\lib\ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'remove_cloud_delay' in section: 'downloads'
```

After I added "remove_cloud_delay" to the settings file (copied from template settings file) the same error happened for "download_rss". After I added both, everything seems to be working again.

**Comment by neox387** [comment]
That is expected if you don't use the update function and manualy do Git pull. 

However I'm using windows have not tested on Linux and Docker it might not work there.

**Comment by cremor** [comment]
I didn't do a manual update. I installed Premiumizer with the setup linked in the readme and it updated itself.

**Comment by neox387** [comment]
Did you change premiumizer service in services.msc to login with an admin account?

It might not have permissions otherwise

**Comment by neox387** [comment]
Or it might be something else, update/restart code is in utils.py and that wont log what went wrong to the log :(

**Comment by cremor** [comment]
I didn't change anything for the service. Right now it runs as local system.

**Comment by neox387** [comment]
mm OK, think I added the admin login because else network folders don't work I think it was.

Did you rename Premiumizer folder to something else maybe ?

**Comment by neox387** [comment]
I have added a logger to see if utils.py fails named update.log, this will only work in the future tough after u have the next pr and then update again ...
