### ISSUE TITLE
Does it support Medusa ?

### ISSUE THREAD

**Issue by gelsas** [piejanssens/premiumizer#125]
https://github.com/pymedusa/Medusa

**Comment by neox387** [comment]
This is something like sonarr?

Idk what it does search for torrent and then what... 

If it can do Blackhole aka drop The torent in a folder then yes it will work Idk about library management we can use nzbToMedia donno of they support medusa

**Comment by gelsas** [comment]
Well it is the better maintained Sickrage (barely updated) and Medusa is updated daily. 
Medusa is from the original Sickbeard developers.

**Comment by neox387** [comment]
Well I left Sickbeard/sickrage years ago for sonarr tv shows and radarr for Movies ^^
