### ISSUE TITLE
Replace "+" with spaces

### ISSUE THREAD

**Issue by Aesir9** [piejanssens/premiumizer#126]
When I search for a movie with radarr, it looks for the original name in the download directory
`Report sent to premiumizer. Guardians of the Galaxy (2014)`
When premumizer downloads the movie it replaces all spaces with "+"
`Downloading: Guardians+of+the+Galaxy+(2014)`
Radarr looks for the original filename it sent to premiumizer and not the one with the plus sings.
If I rename the folder to the right name, the movie  appears in the activity tab from radarr and gets imported.

Could you add an option to replace "+" with spaces?

Thanks for the awesome software.

**Comment by piejanssens** [comment]
Please specify your OS and file type in the watchdir.

**Comment by Aesir9** [comment]
OS: Windows 10
Commit: 7d11f63
`INFO : Added: Guardians+of+the+Galaxy+(2014) -- Category: movie -- Type: Torrent`
`INFO : Downloading: Guardians+of+the+Galaxy+(2014)`
`INFO : Download finished: Guardians+of+the+Galaxy+(2014) location: D:\downloading\Movies\GuardiansoftheGalaxy(2014`
I forgot to mention it creates a folder without spaces or plus sings as you can see.

**Comment by piejanssens** [comment]
@neox387 Sorry to ping you here, I'm assuming you missed it the first time.

**Comment by neox387** [comment]
No did not miss it just didnt get to my pycharm yet to test stuff

**Comment by neox387** [comment]
Well see if you still have this problem after PR It should not show + but it probably wont create a space...

the root of the problem is in the metainfo of the torrent file tough I think.. I also use radarr with rarbg and did not have this happen yet.

**Comment by neox387** [comment]
Alright change wasnt what I tought it would
Do Uri decoding not working, need to check again

**Comment by kungfoolfighting** [comment]
Has there been a fix for this? It seems to me like I am still getting lots of downloads without spaces.

**Comment by neox387** [comment]
if you are running latest versions and you still have it then no =D

I still have not encountered this problem, must be your indexer ? rarbg has . instead of +

**Comment by piejanssens** [comment]
@Aesir9 Do you still encounter this issue after updating to the latest version?

**Comment by Aesir9** [comment]
Not anymore, you can close this issue. Will update it if it happens again.
