### ISSUE TITLE
Can't Download with JDownloader AND Aria2

### ISSUE THREAD

**Issue by Serverfrog** [piejanssens/premiumizer#127]
I don't identify what could be the  Problem with JDownloader. No Errors, nothing. It just don't put the Links into JDownloader.

With Aria2 its simple.
Following Errors in Log.

`09-16 20:39:59: INFO : Running at /opt/premiumizer`
`09-16 20:39:59: ERROR : Could not connect to Aria2 RPC: http://localhost:6800/rpc --- message: global name 'cfg' is not defined`
`09-16 20:39:59: INFO : Starting server on 0.0.0.0:5000 `
`09-16 20:40:12: ERROR : Error for magnet:?xt=urn:(download): Nothing to download .. Filtered out or bad torrent/nzb ?`
`09-16 20:40:12: WARNING : Retrying failed download in 10 minutes for: magnet:?xt=urn:(download)`
`09-16 20:49:44: INFO : Task: (download) -- Category set to: default`
`09-16 20:50:13: ERROR : Error for magnet:?xt=urn:(download )Nothing to download .. Filtered out or bad torrent/nzb ?`
`09-16 20:50:13: ERROR : Download failed for: magnet:?xt=urn:(download)`
`09-16 20:50:13: ERROR : Error for (download ): Nothing to download .. Filtered out or bad torrent/nzb ?`
`09-16 20:50:13: WARNING : Retrying failed download in 10 minutes for: (download)`
`09-16 20:50:33: INFO : Settings saved, reloading configuration`
`09-16 20:50:39: INFO : Settings saved, reloading configuration`
`09-16 20:50:39: ERROR : Could not connect to Aria2 RPC: http://localhost:6800/rpc --- message: unsupported operand type(s) for +: 'int' and 'str'`

Aria Started with `: aria2c --enable-rpc --rpc-allow-origin-all --rpc-listen-all --rpc-listen-port=6800 --rpc-secret=mypassword`

**Comment by neox387** [comment]
Weird will check again when I have time but
global name 'cfg' is not defined

Seems wrong.. The rest of your config is loaded in the settings page?

**Comment by Serverfrog** [comment]
Also, this seems like the problem with the message that cfg is not existing, its far to early:
https://github.com/piejanssens/premiumizer/blob/7d11f630037f2055a67ddb41cd1039686926d239/premiumizer.py#L268

**Comment by Serverfrog** [comment]
The Problem is/was wrong permissions for the Folder / devices was not mounted. Premiumizer don't/can't check these

**Comment by neox387** [comment]
So it works again except for the cfg error?

**Comment by Serverfrog** [comment]
Yes. And The pull request is to fix that Problem

**Comment by neox387** [comment]
fixed in PR #130
there was another issue with download limit not being set at all in aria .. forgot to test with download limit enabled when i wrote the aria2 code =D
