### ISSUE TITLE
Updating to latest version failed

### ISSUE THREAD

**Issue by ip-stivi** [piejanssens/premiumizer#132]
Hi, I was running Update from the web interface but terminal presents me with the below after it didn't come back:

10-13 15:06:46: INFO : Starting server on 192.168.1.2:5000 
Updating 55b9ba8..bf5673f
error: Your local changes to the following files would be overwritten by merge:
 premiumizer.py
 requirements.txt
 settings.cfg.tpl
 templates/index.html
Please commit your changes or stash them before you merge.
Aborting

thank you

**Comment by neox387** [comment]
Well some Git failure or You made changes like it says..

Think you will have to update from terminal/cmd in the premiumizer folder

Something like

git reset --hard
git pull

**Comment by ip-stivi** [comment]
awesome thank you!
