### ISSUE TITLE
Docker container - update problem:  git fetch failed

### ISSUE THREAD

**Issue by Flobbes** [piejanssens/premiumizer#134]
Today I stumbled upon your nice little project.

I have installed the docker container from my synology nas.
I had to manually set the TZ environment variable, but then the container started and works properly.

The only problem I found, is the update mechanism.
I get the following messages during the startup of the process and when trying to update:

> 10-29 18:56:55: ERROR : Update failed: could not git fetch: /premiumizer
10-29 19:04:03: INFO : Settings saved, reloading configuration
10-29 19:04:03: ERROR : Update failed: could not git fetch: /premiumizer
10-29 19:05:22: INFO : Settings saved, reloading configuration
10-29 19:05:22: ERROR : Update failed: could not git fetch: /premiumizer

When I had a closer look at the container, it looks like git isn't installed, which would explain the error.

Is that correct or did I do something wrong during the installation of the container?

**Comment by neox387** [comment]
Well yes Git is needed but never tried Docker so donno.

Maybe @piejanssens knows

**Comment by piejanssens** [comment]
Assuming you have already Installed git (e.g. package from Synocommunity)

Does it help if you add the following to `/etc/profile`?
1. SSH into your Syno
2. Execute `sudo vi /etc/profile`
3. Press `i`key to insert text and move your cursor to the `PATH=` position
4. Add `/usr/local/git/bin`to the PATH so that it looks like 
`PATH=/usr/local/git/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin`
5. Press ESC, enter `:wq` and confirm with <enter>
6. Execute `source /etc/profile`

You can test by entering `git --version`and it should show you installed git version.
If this is a success try the update again and let us know!

**Comment by Flobbes** [comment]
I don't think that will have any effect, if I have understood the docker concept correctly.

I have installed git on the synology nas. But I'm in the docker container environment, therefore I won't be able to access the outside. And I don't want to mount my complete synology environment inside the docker container, because this would bypass all security concepts.

In my oppionion the correct approach would be to add git as part of the docker container.

**Comment by piejanssens** [comment]
@kungfoolfighting @disrupted Any idea how we can support auto update in the docker container?

**Comment by kungfoolfighting** [comment]
@piejanssens @flobbes
Adding git to the container would probably work, BUT: That's not how containers are supposed to work. Having an autoupdate mechanism inside a container means that the contents of the container are not static. Containers are meant to be static and any dynamic content is supposed to be saved to volumes. Containers are supposed to be quickly created and deleted and always have the same behavior. This would no longer be true if you did updates in your container.
If you want autoupdates for the programs in your containers you want to automatically update the whole container, not just the application inside the container. Watchtower is a software that does that and which I use.

Hope this helps.

**Comment by Flobbes** [comment]
Ok. Good to know.

But that would mean several things:

- The configuration shouldn't be stored inside the container but in a volume, because otherwise it's gone with every new container update.

- Everytime there is a git update, a new container has to be deployed?

- If not modified, the software, when executed in a docker container will still try to make updates all the time and will notify the user that there has been an error and updating failed.

**Comment by kungfoolfighting** [comment]
> * The configuration shouldn't be stored inside the container but in a volume, because otherwise it's gone with every new container update.
Yep.
> * Everytime there is a git update, a new container has to be deployed?
Exactly
> * If not modified, the software, when executed in a docker container will still try to make updates all the time and will notify the user that there has been an error and updating failed.
This is true as long as the software does not provide a configuration option to not autoupdate. Many other docker projects have that exact same behavior.

The things you have described are exactly how docker containers are supposed to work. They are supposed to be temporary (volatile) deployments of a software state. You can run them permanently but updating should involve deploying a new container. Think about the problems with container backups that could arise otherwise.

**Comment by piejanssens** [comment]
So this means for Premiumizer we need:
- logic to detect mapped volumes?
- logic to detect docker and not auto update, only display updates

**Comment by neox387** [comment]
It does not auto update, only if you enable it

**Comment by Flobbes** [comment]
> 
> 
> It does not auto update, only if you enable it

You are right. But it automatically does git fetches and fails on them, which is written to the log file and in the settings menu.

**Comment by neox387** [comment]
Ye settings.cfg and .log changes

**Comment by kungfoolfighting** [comment]
I guess the only change "needed" would be not to try and fetch. Detecting docker or volumes is impossible I think. I don't really know what the best way to handle this is. You might still want to display pending updates in the UI, but I guess that requires git fetches. Otoh that then also leads people to try and update the software via the UI, which they shouldn't. So I guess I would actually just turn everything update related off. (Both the autoupdating AND the update notification)

**Comment by Flobbes** [comment]
On stackoverflow I found a solution to detect if running in docker:
https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

There is although a python specific solution in that thread.
https://stackoverflow.com/a/42674935

I justed tested /proc/1/cgroup inside and outside of docker.
You can indead differentiate if you are inside the container.

**Comment by neox387** [comment]
Next PR should be detected based on above link or running with Premiumizer,py --docker to not do any update fetching or pull.

**Comment by Flobbes** [comment]
Just tested it, works perfectly.

Thanks.

**Comment by kungfoolfighting** [comment]
Should this issue be closed?
