### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by bjsjr** [piejanssens/premiumizer#136]
Premiumizer has been working great for me for sometime but now all of a sudden it has stopped downloading.  It still sends the magnet file to Premiumize.me and downloads into my cloud but premiumizer never downloads it to my local system.  The Premiumizer home page loads but just displays "Loading Download Tasks" with the spinning gear.

After enabling Debug mode I found the following error over and over in the log:

```
11-20 17:52:24       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
11-20 17:52:24       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2018-11-20 17:52:25.534319-05:00 (in 0.998979 seconds)
11-20 17:52:24       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2018-11-20 17:52:25 EST)" (scheduled at 2018-11-20 17:52:24.534319-05:00)
11-20 17:52:24       root                                     : DEBUG    : def update started
11-20 17:52:24       root                                     : DEBUG    : def prem_connection started
11-20 17:52:24       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
11-20 17:52:24       root                                     : DEBUG    : def parse_task started
11-20 17:52:24       root                                     : DEBUG    : def get_task started
11-20 17:52:24       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2018-11-20 17:52:25 EST)" raised an exception
Traceback (most recent call last):
  File "/home/openhab/premiumizer/env/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/openhab/premiumizer/premiumizer.py", line 1227, in update
    idle = parse_tasks(transfers)
  File "/home/openhab/premiumizer/premiumizer.py", line 1310, in parse_tasks
    speed=speed + ' --- ', eta=eta, folder_id=folder_id, file_id=file_id)
UnboundLocalError: local variable 'eta' referenced before assignment
11-20 17:52:25       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
```

Any suggestions as to what might be happening?  It was working fine until last night, at least that's when I noticed it.

Thanks!

**Comment by neox387** [comment]
Easy bug fix when I'm at my computer..

Just restart or stop delete .db file and start again for now should work.

**Comment by bjsjr** [comment]
Thanks for the quick response but stopping and deleting premiumizer.db did not help.  I'm still getting the same error.

No hurry, whenever you get a chance to check it out will be fine.

**Comment by neox387** [comment]
Ye I see, premiumize.me doesn't give a proper response to what eta should be and there is no default value for eta so we error.

Problem for that specific Download or for everything, maybe temporarly on premiumize.me side or they changed api response :D

Will fix tomorrow

**Comment by neox387** [comment]
should be fixed next PR

**Comment by bjsjr** [comment]
Any chance the ETA fix could have caused problems with Aria2?  Ever since I applied the fix premiumizer is downloading the same torrents over and over, even after successfully downloading them.  On one of them the download actually fails and for ETA on the premiumizer download screen it displays:
```
Speed: 0 bytes/s --- Size: 0 bytes / 932.1 MB --- ETA: aria2 error
```
My premiumizer log is full of the following errors:
```
1-23 01:30:21: WARNING : Download: XXX.S05E13-E14.HDTV.x264-W4F[rarbg] stuck restarting task
11-23 01:30:25: INFO : Downloading: XXX.S05E13-E14.HDTV.x264-W4F[rarbg]
11-23 01:33:36: WARNING : Download: XXX.S05E13-E14.HDTV.x264-W4F[rarbg] stuck restarting task
11-23 01:33:40: INFO : Downloading: XXX.S05E13-E14.HDTV.x264-W4F[rarbg]
11-23 01:36:51: WARNING : Download: XXX.S05E13-E14.HDTV.x264-W4F[rarbg] stuck restarting task
11-23 01:36:55: INFO : Downloading: XXX.S05E13-E14.HDTV.x264-W4F[rarbg]
11-23 01:37:51: WARNING : Download: XXX.S05E13-E14.HDTV.x264-W4F[rarbg] stuck restarting task
11-23 01:37:56: INFO : Downloading: XXX.S05E13-E14.HDTV.x264-W4F[rarbg]
11-23 01:41:06: WARNING : Download: XXX.S05E13-E14.HDTV.x264-W4F[rarbg] stuck restarting task
11-23 01:41:11: INFO : Downloading: XXX.S05E13-E14.HDTV.x264-W4F[rarbg]
11-23 01:41:11: INFO : File not downloaded it already exists at: /mnt/tvnfs/XXX.S05E13-E14.HDTV.x264-W4F[rarbg]/XXX.s05e13-e14.hdtv.x264-w4f.mkv
```
It's happening with everything I that's downloading.

Thanks!

**Comment by neox387** [comment]
And only with aria? The download does start in aria or nothing happends?

stuck restarting task

Means premiumizer doesn't know if there is Progress in the download normally connection problem from prem to Downloader, ill test later

**Comment by neox387** [comment]
Oops I see it xD

referenced before assignment

Fixed some of those but created another one -. -

**Comment by neox387** [comment]
alright should be working on next PR, sorry for the delay .. black friday stuff arriving lol =D
