### ISSUE TITLE
Select which files to download

### ISSUE THREAD

**Issue by Threak** [piejanssens/premiumizer#140]
For downloads consisting of multiple files or folders it would be great to be able to select only certain files/folder for download.

Like expanding a download entry in the web interface and having checkboxes for each folder or file. Initially I thought this is what the "Browse" button does

**Comment by neox387** [comment]
Wel, there isn't much Automation in choosing what to download..? :) would work when manually adding something before assigning a category. But to much to program to make this work specialy in html.. Not my favorite xD

There is an option to use file extensions to for example only download mkv files.. Or to not download useless samples if included..
