### ISSUE TITLE
Downloading fails

### ISSUE THREAD

**Issue by ituri** [piejanssens/premiumizer#142]
Hi,

I've installed the recent version. .torrent downloads via the blackhole begin just fine, but premiumizer doesn't seem to download them locally. I enabled debugging and here's what I get:
```
01-07 14:01:00       apscheduler.executors.downloads          : ERROR    : Job "NetBSD-8.0-amd64.iso (trigger: date[2019-01-07 14:01:00 CET], next run at: 2019-01-07 14:01:00 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "premiumizer.py", line 1126, in download_task
    failed = download_process()
  File "premiumizer.py", line 1092, in download_process
    if not greenlet.task.dldir.endswith(name):
AttributeError: 'NoneType' object has no attribute 'endswith'
01-07 14:01:00       concurrent.futures                       : ERROR    : exception calling callback for <Future at 0x7f087a4f0990 state=finished returned list>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 331, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python2.7/site-packages/apscheduler/executors/pool.py", line 20, in callback
    self._run_job_success(job.id, f.result())
  File "/usr/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 90, in _run_job_success
    self._scheduler._dispatch_event(event)
  File "/usr/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 822, in _dispatch_event
    with self._listeners_lock:
  File "/usr/local/lib/python2.7/site-packages/gevent/lock.py", line 233, in __enter__
    return self.acquire()
  File "/usr/local/lib/python2.7/site-packages/gevent/lock.py", line 226, in acquire
    rc = self._block.acquire(blocking)
  File "src/gevent/_semaphore.py", line 211, in gevent.__semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 239, in gevent.__semaphore.Semaphore.acquire
  File "src/gevent/_semaphore.py", line 179, in gevent.__semaphore.Semaphore._do_wait
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 59, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 63, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
LoopExit: This operation would block forever
	Hub: <Hub '' at 0x7f087a5817e0 epoll pending=0 ref=0 fileno=13 thread_ident=0x7f0878a76ae8>
	Handles:
[]
```

Any ideas what's wrong here?

**Comment by neox387** [comment]
Download directory is correct?

**Comment by ituri** [comment]
> Download directory is correct?
Yes. I've set it to /downloads and it's writeable.

**Comment by neox387** [comment]
And any error earlyer then above?

In your Download folder did it make the sub directories tv / movie


Do you always have The error? Try stopping delete premiumizer.db and try again

**Comment by ituri** [comment]
> And any error earlyer then above?

No, even tough I get a slightly different error every time premiumizer tries to restart the failed download:

`01-07 14:58:21       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
01-07 14:58:21       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-01-07 14:58:21 CET)" skipped: maximum number of running instances reached (1)
01-07 14:58:21       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-01-07 14:58:22.507981+01:00 (in 0.997062 seconds)
01-07 14:58:21       apscheduler.scheduler                    : INFO     : Added job "NetBSD-8.0-amd64.iso" to job store "downloads"
01-07 14:58:21       socketio                                 : INFO     : emitting event "tasks_updated" to all [/]
01-07 14:58:21       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:05:00], next run at: 2019-01-07 15:03:21 CET)" executed successfully
01-07 14:58:21       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
01-07 14:58:21       apscheduler.scheduler                    : INFO     : Removed job 305c463ac4ad4624813fce7678848158
01-07 14:58:21       apscheduler.executors.downloads          : INFO     : Running job "NetBSD-8.0-amd64.iso (trigger: date[2019-01-07 14:58:21 CET], next run at: 2019-01-07 14:58:21 CET)" (scheduled at 2019-01-07 14:58:21.819160+01:00)
01-07 14:58:21       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-01-07 15:03:21.849323+01:00 (in 299.998082 seconds)
01-07 14:58:21       root                                     : DEBUG    : def download_task started
01-07 14:58:21       root                                     : DEBUG    : def download_process started
01-07 14:58:21       socketio                                 : INFO     : emitting event "update_task" to all [/]
01-07 14:58:21       root                                     : DEBUG    : def clean_name started
01-07 14:58:21       root                                     : DEBUG    : def to_unicode started
01-07 14:58:21       root                                     : DEBUG    : def prem_connection started
01-07 14:58:21       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/folder/list HTTP/1.1" 200 None
01-07 14:58:21       root                                     : DEBUG    : def processing_dir started
01-07 14:58:21       apscheduler.executors.downloads          : ERROR    : Job "NetBSD-8.0-amd64.iso (trigger: date[2019-01-07 14:58:21 CET], next run at: 2019-01-07 14:58:21 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "premiumizer.py", line 1126, in download_task
    failed = download_process()
  File "premiumizer.py", line 1110, in download_process
    process_dir(dir_content, greenlet.task.dldir)
  File "premiumizer.py", line 1072, in process_dir
    if x['link'].lower().endswith(tuple(greenlet.task.dlext)):
`

> In your Download folder did it make the sub directories tv / movie

No, it was created by premiumizer. But it's there and it's writeable. There's also a default folder which the above file should be downloaded in because I enabled the option to _Download everything and assign the category 'default'_.


> Do you always have The error? Try stopping delete premiumizer.db and try again

Oh, that did the job! Any ideas why I had to do that?
Thanks!

**Comment by ituri** [comment]
I understand. Thanks for clearing that up!

**Comment by ituri** [comment]
Unfortunately, I still keep getting this issue. Everytime I add a download, Premiumizer gets stuck after the download on premiumize has finished and before it is downloaded to my computer. For each download, I then need to delete premiumizer.db.

Any ideas what could be the issue here and how I can fix that?

**Comment by neox387** [comment]
It has to be something in the Path, if you have a nas or some other device could try to download to that.. \\nas\download

or maybe shelf database that somehow doesn't want to work on your os.

I still have not tried running on a Linux distro.

**Comment by ituri** [comment]
It's running in the docker image on a Synology NAS, so that's Linux. Does that help?

**Comment by neox387** [comment]
Well there are others that are running it on Docker. But didnt hear of these kind of problems yet ^^

**Comment by neox387** [comment]
@ituri still not working with latest version?
