### ISSUE TITLE
Pausing Download

### ISSUE THREAD

**Issue by kungfoolfighting** [piejanssens/premiumizer#143]
I would like to be able to temporarily pause the download from premiumize.me to my hard drive and then resume it later.
Currently I can only "Stop Download" which stop the download and removes it from the drive. It also doesn't allow me to restart it.
So it would be great to have both the functionality to restart after stopping and to also pause and resume.
cheers!

**Comment by piejanssens** [comment]
Isn't this possible with Aria2?

**Comment by neox387** [comment]
Stopping should clear the category, so if you select a category it should restart The download

Pause/resume with built in Downloader this does not work, with Aria2 and jdownloader it should work but the code isn't active so probably needed more work:

# @socketio.on('pause_task')

**Comment by neox387** [comment]
fixed this, try after next PR.. only for aria2 and jDownloader.

pause on built in downloader (pysmartDL) just does not work.

Will need to update requirements because new version for myjdapi for jDownloader to make this work..
