### ISSUE TITLE
Synology Docker - Blackhole folder not working

### ISSUE THREAD

**Issue by ujellyx** [piejanssens/premiumizer#144]
Today I tried configuring Premiumizer with Sonarr on my NAS, but seem to be stuck on some settings as it seems.

I configured the volume/folders on the docker image as followed:
![docker-volume](https://user-images.githubusercontent.com/17804807/52162607-0a0da000-26d7-11e9-825b-36d124730edb.png)

The settings inside Premiumizer then are set to reflect these folders:
![premiumizer-settings](https://user-images.githubusercontent.com/17804807/52163032-5d362180-26dc-11e9-94f8-c83572e4f033.png)

And finally inside Sonarr I set it up like this:
![sonarr-client-settings](https://user-images.githubusercontent.com/17804807/52163033-62936c00-26dc-11e9-81b8-abe8acfa0ce6.png)

The .torrent/.magnet files are placed properly inside the specified /torrents/tv-folder by Sonarr, but after this, nothing else happens as Premiumizer doesn't seem to notice the new files.
Manually adding the .torrent/.magnet files to Premiumizer works and downloads the files just fine after manually setting a category.

Did I miss something? Did I maybe use the wrong "syntax" in the "folders to watch" field for the "Watchdir - Blackhole"? I also tried just using "torrents" inside the field, but that didn't change anything.

I'd appreciate any help.

**Comment by neox387** [comment]
Might be some permissions/user issue. 

Maybe #88 has some helpfull info?

Could also try debug mode and see if you get some error.

**Comment by ujellyx** [comment]
Given the fact that it can write to the download-folders just fine, I doubt that this is a permission-error though. Maybe Premiumizer creates an own/default blackhole folder by default? If so, I'd need to know the path of it, so that I can map it for other docker images (Sonarr).

**Comment by neox387** [comment]
It will create the sub directories itself,

So if you set it to torrents that is linked in Docker to downloads/torrents. Premiumizer will try to create downloads/torrents/tv and movie

**Comment by ujellyx** [comment]
Setting it to "torrents" or "downloads/torrents" seems to be accepted by Premiumizer, according to the log:

> 02-02 11:50:43: INFO : Watchdir is enabled at: torrents
or
> 02-02 12:00:50: INFO : Watchdir is enabled at: downloads/torrents

The torrent/magnet files inside the folder (and sub-folders tv/movie) aren't noticed though and no download is starting automatically.

**Comment by neox387** [comment]
Then I donno someone running on Docker might know more =D

**Comment by cremor** [comment]
Did you set PGID and PUID to values that represent a user that has access to the folder?

Otherwise, try my settings here: https://github.com/piejanssens/premiumizer/issues/88#issuecomment-462498224

**Comment by ujellyx** [comment]
@cremor Yeah I have set PGID and PUID to the administrator-user values, just like my other working docker containers. Tried it with and without (back-)slashes, didn't change anything :/

**Comment by Flobbes** [comment]
It put the absolut file paths everywhere with / everywhere and its working fine.
Your info log looks a bit strange with missing slashes at the beginning, don't know if thats the problem. Like cremor mentioned I get the correct absolute path as well in the log.

**Comment by ujellyx** [comment]
> It put the absolut file paths everywhere with / everywhere and its working fine.
> Your info log looks a bit strange with missing slashes at the beginning, don't know if thats the problem. Like cremor mentioned I get the correct absolute path as well in the log.

Can you post a screenshot of your docker settings - especially the volume mappings?

**Comment by Flobbes** [comment]
![screenshot from 2019-02-12 18-28-22](https://user-images.githubusercontent.com/13646589/52656049-d6f8b700-2ef5-11e9-8ab8-2ec322e15d5e.png)

**Comment by piejanssens** [comment]
Please try with the latest version and map /conf + /downloads + /blackhole
