### ISSUE TITLE
Restructuring project files

### ISSUE THREAD

**Issue by piejanssens** [piejanssens/premiumizer#147]
I would like to clean up the structure a bit.
- app
    - \_\_init\_\_.py
    - docker-entrypoint.sh
    - *.py
    - static
    - templates
- conf
    - settings.cfg.tpl
- requirements.txt
- .gitignore
- Dockerfile
- License
- Readme

What should be take into account? 
This will break installations, unless we can come up with a way to migrate?

**Comment by neox387** [comment]
Config folder would work with update, moving py files would break more stuff =D

**Comment by neox387** [comment]
and it's done.

I have also made a new https://github.com/neox387/PremiumizerInstaller since the path for the service changed

**Comment by neox387** [comment]
small code include to move settings from root to conf folder if detected.

using update function will not be able to restart tough since it does not know to start .py from new location.
