### ISSUE TITLE
Error on Download

### ISSUE THREAD

**Issue by speedy80** [piejanssens/premiumizer#15]
I get the following error and files are never downloaded:

> 3-18 22:45:13       apscheduler.executors.download           : ERROR    : Job "XXX (trigger: date[20
16-03-18 22:45:13 CET], next run at: 2016-03-18 22:45:13 CET)" raised an exception
Traceback (most recent call last):
  File "/home/patrick/.local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 112, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "Premiumizer.py", line 400, in download_task
    failed = download_file(download_list)
  File "Premiumizer.py", line 336, in download_file
    downloader = SmartDL(download['url'], download['path'], progress_bar=False, logger=logger, threads_count=1)
TypeError: __init__() got an unexpected keyword argument 'threads_count'

>

**Comment by neox387** [comment]
This is probably cause your version of pysmartdl is incorrect, did you pip install - r requirements.txt? And have Git installed? Pip list to see if pysmartdl is version 1.2.5. 

If so uninstall &  reinstall requirements.txt or Pip install https://github.com/neox387/pySmartDL/archive/master.zip

**Comment by speedy80** [comment]
You are right – replaced pysmartdl as version 1.2.4 was installed and it works now.

Thank you for your help and for this Software. Find it great!
