### ISSUE TITLE
Outdated pySmartDL

### ISSUE THREAD

**Issue by piejanssens** [piejanssens/premiumizer#151]
@neox387 Seems pySmartDL has come back to live.
Can you compare your forks changes to the latest upstream master and cherry pick the necessary fixes/improvements to create PR's to the upstream master?

**Comment by neox387** [comment]
I see .. nice

also things I did are already included I see:
-update user agents
-specify thread count
-better combining files
-enable limit speed option altough with this one I see a diffrent line 478:
self.thread_shared_cmds['limit'] = 1024.0*kbytes/self.threads_count

He didn't do 1024 so need to test if it's right now


but changelog:
- NEW: Added support for Python 3.7.
- NEW: Dropped support for Python 2 and 3.1, 3.2, 3.3.

so need to test if it still works on 2.7 ..

we should update to python 3.x maybe ..

**Comment by neox387** [comment]
never mind updating to python 3, bunch breaks =D

**Comment by neox387** [comment]
tested new pySmartDL but it indeed does not run anymore on 2.7..
