### ISSUE TITLE
Migration to Python 3

### ISSUE THREAD

**Issue by piejanssens** [piejanssens/premiumizer#152]
Not imminent, but some day this has to happen.

Current situation on dependencies (caniusepython3):
```
[WARNING] Skipping 'https://github.com/neox387/pySmartDL/archive/1.2.7.zip': could not parse requirement
[WARNING] Skipping 'https://github.com/neox387/myjdapi/archive/1.0.7.zip': could not parse requirement
Finding and checking dependencies ...

You need 4 projects to transition to Python 3.
Of those 4 projects, 4 have no direct dependencies blocking their transition:

  bencode
  flask-reverse-proxy
  gevent-websocket
  pathtools
```
- pySmartDL --> switch to upstream master (requires Python 3)
- myjdapi --> switch to upstream master (supports Python 2 and Python 3)
- bencode --> switch to bencode-python3 (supports Python 2 and Python 3)
- flask-reverse-proxy --> ?
- gevent-websocket --> ? (Does it really not work with Python 3?)
- pathtools --> ? (see https://github.com/gorakhargosh/pathtools/issues/4)

**Comment by neox387** [comment]
mkay working on it 
https://github.com/neox387/premiumizer/tree/py3

**Comment by neox387** [comment]
can close #151

**Comment by neox387** [comment]
and it's done =D, also fixt some bugs like filehost wasn't working anymore.

this will obviously break all running premiumizers on python 2
