### ISSUE TITLE
Can't start docker image

### ISSUE THREAD

**Issue by kungfoolfighting** [piejanssens/premiumizer#153]
The last update from two days ago seems to have broken my premiumizer setup. When I try to run the container it says this in the logs:
`2019-02-21T15:40:40.033990502Z  python: can't open file 'premiumizer.py': [Errno 2] No such file or directory`

Any idea what is wrong?

**Comment by neox387** [comment]
Yes the .py file moved to a folder and so did the settings.cfg

but I tought new dockerfiles should have the right location.

maybe start over not sure not using docker =D

**Comment by kungfoolfighting** [comment]
I did fix the settings folder location because I found that change in the commits, but I didn't see anything about the py file location except that the start script calls it from a different location now, but that should just work, right? Is this perhaps an access rights issue?  
I always completely recreate the container as per the standard docker procedure and I still get this issue.
What might the extra steps be, that I need to take to get this to work?

**Comment by kungfoolfighting** [comment]
After a bit of experimentation I seem to have found the culprit.
I opened an interactive shell inside the running container and tried to start premiumizer via the docker-entrypoint.sh script. This succeeds when called from the /premiumizer folder. It fails when called from the root directory. I then looked at the entrypoint script inside the container and the relevant like looks like this:
`su - premiumizer -p -c 'python premiumizer.py'`
This is different than the line that is on github, which is:
`su - premiumizer -p -c 'python ./premiumizer/premiumizer.py'`

I really don't know why.
I created a fresh container with:
`sudo docker run --rm -it --entrypoint=/bin/sh piejanssens/premiumizer`
So it should be the latest image from the docker hub. The docker hub also shows that the last built version is the latest commit of the master branch which includes the fix for this. 
What is going on here? Was there an issue during the build of the image?

**Comment by kungfoolfighting** [comment]
So I fixed this by manually deleting the existing image on my device  and then doing another run of the container so it would be downloaded again from the hub.
I have no idea why. The image list of docker actually said it had downloaded it two days ago, so pretty much when the newest image was built. Redownloading it fixed it though, so... I don't know what happened.

**Comment by piejanssens** [comment]
@kungfoolfighting The fix for the entrypoint script came in later than the restructuring of our application files. Very probable that you created an image between those PR's.
