### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by audioslayer** [piejanssens/premiumizer#155]
It looks like I have having a permission error with setting my download folder location. This is my log, I am running Ubuntu 18.04 LTS, Any Help would be great.

02-25 01:53:33: INFO : Settings saved, reloading configuration
02-25 01:53:33: INFO : Creating Download Path at: /home/tyson/Downloads/1/tv
02-25 01:53:33: ERROR : Cannot Create download directory: /home/tyson/Downloads/1/tv --- error: [Errno 13] Permission denied: '/home/tyson/Downloads' 

Oh im starting it with,

sudo docker run -d -p 5000:5000 -e TZ=Europe/London -e PUID=1000 -e PGID=1000 -v premiumizer:/premiumizer/conf -v premiumizer:/blackhole -v premiumizer:/downloads repo/tag

**Comment by Chemsorly** [comment]
it looks like you are bind mounting all three folders (conf, blackhole and downloads) into the same folder on the host (premiumizer). Try using separate folders, e.g. ```-v /premiumizer/conf:/premiumizer/conf -v /premiumizer/blackhole:/blackhole -v /premiumizer/downloads:/downloads```. You also might need to create the ```/premiumizer``` folder and set permissions with ```sudo chown -R 1000:1000 /premiumizer```

**Comment by audioslayer** [comment]
Yup That was the problem. Thanks, All is up and running.

**Comment by piejanssens** [comment]
Thanks for helping out @Chemsorly
