### ISSUE TITLE
Can't Start Premiumizer Service Windows 10

### ISSUE THREAD

**Issue by chest069** [piejanssens/premiumizer#156]
I was using the previous version of premiumizer and installed the newest version of premiumizer and now when the install completes and tells me to start the service I can't in windows 10.

I did this with the windows installer from the website.

What do I need to do or try. Thanks for any help.

**Comment by neox387** [comment]
Wait for #154
Installer is updated for Python3

**Comment by chest069** [comment]
So does this mean that I have to wait until the installer is updated to python 3, the installer it is already updated to python 3 and I have to wait for other stuff to be updated for it to work, or do I need to just install python 3 manually. Sorry but I don't understand the point you made. Thanks for the help.

**Comment by neox387** [comment]
Uninstall and install again with same installer.

It will work now as the PR is merged.

**Comment by chest069** [comment]
Ok, I Will do that. Thanks.

**Comment by chest069** [comment]
Hello,
I tried to install again using the installer and got the following errors while installing into Windows 10. Hopefully you can view the pictures.
The last two happen after it completes the first I think is supposed to be the config file that I have to change and the second is me trying to start the service.
Any ideas? Thanks for any help.
Also do I need to be doing the installer as "Run As Administrator"

![image](https://user-images.githubusercontent.com/661946/53728749-6e8c5e00-3e41-11e9-9077-0286d2053d0c.png)
![image](https://user-images.githubusercontent.com/661946/53728779-7946f300-3e41-11e9-9d86-82ea0dc425bf.png)
![image](https://user-images.githubusercontent.com/661946/53728791-806e0100-3e41-11e9-9720-87a191f4e4c5.png)
![image](https://user-images.githubusercontent.com/661946/53728799-8663e200-3e41-11e9-861c-5fea9303715a.png)
![image](https://user-images.githubusercontent.com/661946/53728815-8e238680-3e41-11e9-95f9-989aa75372b7.png)
![image](https://user-images.githubusercontent.com/661946/53728834-98458500-3e41-11e9-9fcb-89f3a602ee03.png)

**Comment by neox387** [comment]
Mm you can try to install as admin normally should't be needed. 

Try from config panel and uninstall software: 
Premiumizer
Git 
Python

So it can start over. 

If you install you should see it downloads Git and python and then installs them.

**Comment by chest069** [comment]
Thanks for the reply.

Removed Premiumizer, Git, and Python then reinstalled it and then restarted my computer and that worked. So apparently you have to do a complete clean install first.

So quick question in settings it says I can add my jdownloader info but where can I find the username, password, and device name.

Thank you for your help on this. You were great.

**Comment by neox387** [comment]
In Jdownloader is a tab called My.jdownloader

You might need to make a new account there.
