### ISSUE TITLE
Docker - Uncaught exception

### ISSUE THREAD

**Issue by MasterIpse** [piejanssens/premiumizer#157]
When I start the container it crashes with an uncaught exception:
```
usermod: no changes
03-05 10:28:57: INFO : Running at /premiumizer
------------------------------------------------------------------------------------------------------------
| |
-------------------------------------------WELCOME TO PREMIUMIZER-------------------------------------------
| |
------------------------------------------------------------------------------------------------------------
03-05 10:28:57: ERROR : Uncaught exception

Traceback (most recent call last):
File "./premiumizer/premiumizer.py", line 427, in <module>
cfg = PremConfig()
File "./premiumizer/premiumizer.py", line 223, in __init__
self.check_config()
File "./premiumizer/premiumizer.py", line 229, in check_config
if prem_config.getfloat('update', 'req_version') < default_config.getfloat('update', 'req_version'):
File "/usr/local/lib/python3.7/configparser.py", line 823, in getfloat
fallback=fallback, **kwargs)
File "/usr/local/lib/python3.7/configparser.py", line 808, in _get_conv
**kwargs)
File "/usr/local/lib/python3.7/configparser.py", line 802, in _get
return conv(self.get(section, option, **kwargs))
File "/usr/local/lib/python3.7/configparser.py", line 780, in get
d = self._unify_values(section, vars)
File "/usr/local/lib/python3.7/configparser.py", line 1146, in _unify_values
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'update'
```

**Comment by neox387** [comment]
configparser.NoSectionError: No section: 'update

Problem with config file: is it there in config folder..? Does it have an update section?

**Comment by MasterIpse** [comment]
The docker broke after the last update, before I had a functioning config file. (This one also had the update section.)

I tried creating a new instance and put the default config file into the config directory.
It has the update section:
`[update]
updated = 0
auto_update = 0
update_date = Never
config_version = 2.1
req_version = 8.1`

**Comment by neox387** [comment]
Do You still have settings.cfg.tpl in the folder?

**Comment by MasterIpse** [comment]
Well now I'm confused - for my old docker I had a "settings.cfg" and not "settings.cfg.tpl".

I have now changed the name for the new docker to "settings.cfg.tpl", no uncaught exception anymore.
But somehow I only get "connection refused" in my browser.
I seem to be slow on the uptake... I'll check everything with fresh eyes tomorrow.

**Comment by neox387** [comment]
Both files should be in there xD, before update settings.cfg.tpl did not need to be.

Could make a small adjustment so it's again not required any more..

**Comment by MasterIpse** [comment]
Ah ok, so with both files in the /config folder, the container itself starts up:
Docker command:
`docker run -d --name='premiumizer' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -p '5000:5000/tcp' -v '/xxx/blackhole/':'/blackhole':'rw' -v '/xxx/premiumizer/':'/premiumizer/conf':'rw' -v '/xxx/DOWNLOAD/':'/downloads':'rw' -e PUID=1000 -e PUID=1000 'piejanssens/premiumizer:latest' `

Log:
`usermod: no changes
03-07 00:22:36: INFO : Running at /premiumizer
03-07 00:22:36: INFO : Starting server on 127.0.0.1:5000
03-07 00:22:46: ERROR : premiumize.me login error: {"status":"error","message":"Not logged in. Please log in first."}`

But somehow I get "Connection refused" errors when I try to connect to it via browser.

(Thank you for the help!)

**Comment by piejanssens** [comment]
Don't think it will help with your issue, but AFAIK It should be mount '/xxx/premiumizer/' to '/conf'.

**Comment by neox387** [comment]
Starting server on 127.0.0.1:5000 

If he is using older settings.cfg je needs to adjust this also to 0.0.0.0 then..?

**Comment by piejanssens** [comment]
Yes. I have set it to 0.0.0.0 by default now as you can see in the commits.

**Comment by piejanssens** [comment]
@MasterIpse Can you give the latest Docker image a go?

**Comment by MasterIpse** [comment]
I've now tested the new commit and made it work as followed:
- Started the container without mounting conf to host
- ssh'ed into the container and copied database.db, logs and settings.cfg to my desired host path
- mounted "/premiumizer/conf" to that host path

**Comment by piejanssens** [comment]
Glad to hear! Thanks for reporting back.
