### ISSUE TITLE
Premiumizer is already installed. Error but it is not.

### ISSUE THREAD

**Issue by gelsas** [piejanssens/premiumizer#158]
I am getting this error: 
Premiumizer is already installed. If you're reinstalling or upgrading, please uninstall the current version first.

It is not installed and I have no Idea what I could do now. So what to do now ?

**Comment by neox387** [comment]
Is this the installer for windows?

If you see c:\premiumizer? then something is probably installed... 

Try config panel and uninstall software
If you see
Premiumizer
Python
Git

Remove these and try to install again..

**Comment by gelsas** [comment]
No there is nothing 
Also nothing shown in uninstall software

**Comment by gelsas** [comment]
This is the setup log: https://pastebin.com/raw/k2L8WicX

**Comment by gelsas** [comment]
Fixed it by installing the program on another computer and then copy the uninstaller over to my system and ran it. Now installing works again.
