### ISSUE TITLE
Add systemtray

### ISSUE THREAD

**Issue by gelsas** [piejanssens/premiumizer#161]
I really love the function of Sonarr or jdownloader to have an icon in the systemtray for quick access.

I would love if such a thing could be added to premiumizer. According to stackoverflow this would be the perfect python solution for it: https://github.com/Infinidat/infi.systray 

When double clicking the icon it could open http://localhost:5000.

What do you think about this ?

**Comment by neox387** [comment]
Quick Google found
https://github.com/moses-palmer/pystray

Says it works on windows, Mac and Linux

Could try to implement this.

**Comment by gelsas** [comment]
That would be really really great

**Comment by neox387** [comment]
Can't get pystray to work cause it runs in blocking mode

infi.systray is non blocking but windows only and seems bit dead so not much use implementing this I think..

@gelsas just bookmark premiumizer in browser toolbar? ^^
