### ISSUE TITLE
Destination Folder Name without spaces

### ISSUE THREAD

**Issue by glenner123** [piejanssens/premiumizer#162]
I get an issue importing completed Premuimizer downloads into both Sonarr and Radarr. It only happens about 10% of the time and it seems to be when the containing folder for file that has been downloaded is named with no spaces. I think Sonarr/Radarr expects the folder to be the same name as the file within so it can't find the file to import. If a manually rename the folder to the same name as the file inside then Sonarr/Radarr will find it and import it. Is the folder name something that is defined during the download process by Premuimizer or is it just something that is defined by a specific torrent release and out of the progrmas control? cheers.

**Comment by piejanssens** [comment]
Log files?
What is the original file name?
What is the filename in the premiumizer download folder?

**Comment by neox387** [comment]
You need to use nzbToMedia, and this tells sonarr radarr what folder, so wrong name should't be possible.

NzbToMedia also has log files

**Comment by glenner123** [comment]
> Log files?
> What is the original file name?
> What is the filename in the premiumizer download folder?

In one example the file passed from Radarr was

Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4 

Once download it was placed within a folder structure of:
Bumblebee20181080pHDRipx264AAC20/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4

If a manually rename the folder to be same as the file name it is imported automatically

section of log file below

03-13 14:44:21: INFO : Using url "https://abby.databypass.com/dl/OkTIqes2HELmjikGSjCjRQ/1553093061/212107641/5c43b04e2b7cf4.00480147/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4"
03-13 14:44:21: WARNING : Server does not support HTTPRange. threads_count is set to 1.
03-13 14:44:21: INFO : Creating a ThreadPool of 1 thread(s).
03-13 14:44:21: INFO : Starting a new SmartDL operation.
03-13 14:44:21: INFO : One URL is loaded.
03-13 14:44:21: INFO : Downloading 'https://abby.databypass.com/dl/OkTIqes2HELmjikGSjCjRQ/1553093061/212107641/5c43b04e2b7cf4.00480147/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4' to '/download/movie/Bumblebee20181080pHDRipx264AAC20/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4'...
03-13 14:44:21: INFO : Content-Length is 1944663921 (1.81 GB).
03-13 14:44:21: INFO : Launching 1 thread.
03-13 14:44:21: INFO : Downloading 'https://abby.databypass.com/dl/OkTIqes2HELmjikGSjCjRQ/1553093061/212107641/5c43b04e2b7cf4.00480147/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4' to '/download/movie/Bumblebee20181080pHDRipx264AAC20/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4.000'...
03-13 14:44:21: INFO : Control thread has been started.
03-13 14:49:41: INFO : File downloaded within 320.42 seconds.
03-13 14:49:41: INFO : Download finished: Bumblebee20181080pHDRipx264AAC20 -- info: 1.81 GB --  5.8 MB/s --  5m20s -- location: /download/movie/Bumblebee20181080pHDRipx264AAC20

**Comment by glenner123** [comment]
> You need to use nzbToMedia, and this tells sonarr radarr what folder, so wrong name should't be possible.
> 
> NzbToMedia also has log files

Thanks,  any ideas on where do start with this? Using all apps within separate dockers on a Synology which was a bit of a learning curve in itself. Bit of a beginner and can't see any suitable NZBToMedia package to install in the Registry.

**Comment by neox387** [comment]
Think you need to do it on terminal and Git clone it inside premiumizer Docker.. Not sure

**Comment by glenner123** [comment]
> Log files?
> What is the original file name?
> What is the filename in the premiumizer download folder?

Ok, so in this example the file was

Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4

once downloaded it ends up in a folder as below

Bumblebee20181080pHDRipx264AAC20/Bumblebee.2018.1080p.HDRip.x264.AAC2.0.LLG.mp4

After having this problem for week  I noticed all the problem ones seemed to be within a folder with no spaces. So i renamed the folder manually and bang it was imported instantly.

As I said this is a random things. Loads of download getting picked up and imported instantly. The one constant is that the ones don't work are in a folder structure with no spaces.

**Comment by glenner123** [comment]
> Think you need to do it on terminal and Git clone it inside Premiumizer Docker.. Not sure

blimey, think that's beyond me at this stage. Will probably just continue to manually import the ones that fail. Just annoying as its so close to a perfect automated workflow for me.

**Comment by neox387** [comment]
It should't remove The dots in folder name Tough some Linux problem maybe, never had this on windows.


But how are they picked up? Drone factory then?

**Comment by glenner123** [comment]
> It should't remove The dots in folder name Tough some Linux problem maybe, never had this on windows.
> 
> But how are they picked up? Drone factory then?

I've set both Sonarr/Radarr to use "Torrent Blackhole" as the download client.  The download client is then configured so the "Torrent Folder setting" is set to the Premiumizer watch folder and the "Watch Folder setting" is set to the Premiumizer download folder. It works great except for this odd issue 10% of the time. Thanks for your comments!

**Comment by glenner123** [comment]
Just had another. However this folder is a different structure. I don't see this is a Premiumizer thing is it? Is it just because Sonarr/Radarr is so very strict and picky on naming?

FOLDER - ASimpleFavor2018PROPER1080pBluRayH264-Favour-GoodFilms
FILE - A.Simple.Favor.2018.PROPER.1080p.BluRay.H264.AAC-RARBG.mp4

**Comment by neox387** [comment]
Mm tought this didnt work because of You start Download it already makes files that sonarr is gonna try to import because it thinks it's New file

**Comment by glenner123** [comment]
So have renamed the folder to add the spaces back in 

ASimpleFavor2018PROPER1080pBluRayH264-Favour-GoodFilms

manually renamed to

A Simple Favor 2018 PROPER 1080p BluRay H264-Favour-GoodFilms

and its now been picked up and imported straight away into Radarr. So it is 100% something to do with the spaces being removed making it not recognised and stopping automatic import

**Comment by piejanssens** [comment]
Could you enable debug logging and send us the log file after reproducing the issue? (new download)

**Comment by glenner123** [comment]
> Could you enable debug logging and send us the log file after reproducing the issue? (new download)

Will do, thanks a lot for looking

**Comment by piejanssens** [comment]
Please confirm the folder and filenames visible in premiumize.me.

**Comment by glenner123** [comment]
> Could you enable debug logging and send us the log file after reproducing the issue? (new download)

Turned on Debug logging and first one I tried worked perfect (as it does most of the time). Placed in watch folder by Radarr, picked up by Premuimize, downloaded, automatically imported back into Radarr.

[premiumizerDEBUG.log](https://github.com/piejanssens/premiumizer/files/2963537/premiumizerDEBUG.log)

**Comment by piejanssens** [comment]
We'll need a debug log when the problem does occur 😄 
@neox387 Seems we lack a ton of debug statements for printing creating paths and renaming files etc.

**Comment by glenner123** [comment]
yeah i know, thought you might want a comparison - 3 files in and still waiting for a failure!

**Comment by glenner123** [comment]
Here you go. 3 files added by Raderr, all picked up by premiumizer, all downloaded, only 2 imported back into Radarr.

Problem File is the following:-
Created Folder: RalphBreaksTheInternet(2018)[BluRay](1080p)[YTSAM]
I manually renamed : Ralph Breaks The Internet (2018) [BluRay] (1080p) [YTS AM]

Imports instantly straight into Radarr automatically

[premiumizerDEBUG.log](https://github.com/piejanssens/premiumizer/files/2963660/premiumizerDEBUG.log)

**Comment by piejanssens** [comment]
Send me that magnet please.

**Comment by glenner123** [comment]
> Send me that magnet file please.

Think its this one. renamed to txt

[636881083170441420-LimeTorrents-Ralph Breaks The Internet (2018) [BluRay] (1080p) [YTS AM].txt](https://github.com/piejanssens/premiumizer/files/2963693/636881083170441420-LimeTorrents-Ralph.Breaks.The.Internet.2018.BluRay.1080p.YTS.AM.txt)

**Comment by neox387** [comment]
Well the name inside The magnet/torrent is without spaces not sure if it can be with spaces?

That's why it's mostly   .    Instead of spaces I Think.

Cause everything You Download has this I see. 

So we need to Change some code that detects to add space between words.. Not sure how without errors.. .. @piejanssens

This happends with add_task
name = urllib.parse.unquote(name)
name = clean_name(name)

**Comment by neox387** [comment]
=Ralph+Breaks+The+Internet+%282018%29+%5BBluRay%5D+%281080p%29+%5BYTS+AM%5D&

The + inbetween shouldnt The proper encoding for space be %20?

Bad indexer I would say use rarbg xd

**Comment by piejanssens** [comment]
Fixed it with https://github.com/piejanssens/premiumizer/commit/04a2a951300ad800e5477f152561798883c562d9

**Comment by glenner123** [comment]
Amazing, thank you both so much for your time, will give it a good test tomorrow

**Comment by neox387** [comment]
A I see magnet gets it's name there..

So reason why it sometimes did not work is maybe cause mostly sonarr should give torrent files and fallsback to saving it as a magnet when it doesn't get torrent from indexer.. Radarr doesn't have this option

**Comment by piejanssens** [comment]
@glenner123 Good. If it's not resolved tomorrow feel free to reopen.
