### ISSUE TITLE
500 Internal Server Error Message When Trying to Update

### ISSUE THREAD

**Issue by chest069** [piejanssens/premiumizer#165]
Hello,
Premiumizer is telling me that I have an update to it and goto settings to update. I try and do this but it comes back with the error listed above. Any ideas on what I should do or how to apply the update manually. Thanks for any help on this.

**Comment by piejanssens** [comment]
No debug logs? No version information?
My guess would be that you are stuck in between updates where the internal updater was broken for a short period: https://github.com/piejanssens/premiumizer/pull/163
Shut premiumizer down, go into your premiumizer installation folder and "git pull" the latest version.

**Comment by chest069** [comment]
Sorry, lost my mind there for a second and forgot you needed all of that information.

I did "git pull" in the program directory and all was cool.

The one thing that I have to do and all the time now when I launch premiumizer is once it opens the web page it shows me an error but if I erase the login part of the address it brings up the interface. (This is in the newest version)

This is all the log shows:
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:19: INFO : ----------------Premiumizer.log file has been deleted as a precaution----------------
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:19: INFO : ---------------Database file has been deleted as a precaution----------------
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:19: INFO : ---------------------------Premiumizer has been updated!!----------------------------
03-19 12:19:19: INFO : *************************************************************************************
03-19 12:19:22: INFO : Starting server on 127.0.0.1:5000 
03-19 12:19:33: ERROR : Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Premiumizer\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Premiumizer\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Premiumizer\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Premiumizer\Python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Premiumizer\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Premiumizer\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Premiumizer\Premiumizer\premiumizer\Premiumizer.py", line 2139, in login
    if username == cfg.web_username and password == cfg.web_password:
AttributeError: 'PremConfig' object has no attribute 'web_username'

**Comment by neox387** [comment]
well made a change to not get that error.

BUT
why are you on a login page if you do not have login enabled =D bookmarked with /login at the back ?

and your error is on line 2139 while om master this is on line 2153 so not sure if you have the latest version, you could just delete everything clone again and put your settings file in conf folder.

**Comment by chest069** [comment]
Yeah, it was bookmarked that way by mistake. doh :)
So after I delete everything what is the best way to do my git pull clone so I can make sure this time it is the right way since what I did last time didn't do anything?
Thanks for help on this.

**Comment by neox387** [comment]
If you on windows? You could remove premiumizer Git and python and reinstall with installer =D

Else well just got clone?.. xD

**Comment by chest069** [comment]
Ok, cool I'll do that. Thanks for the help. (but yeah Windows)

**Comment by piejanssens** [comment]
Glad it's solved. @neox387 Don't we print the version (commit hash) in the debug log?

**Comment by neox387** [comment]
@piejanssens noop it's only displayed on the settings page, so code is there. We should indeed print it in the log
