### ISSUE TITLE
Unresolvable dependency python-socketio<4,==4.0.0

### ISSUE THREAD

**Issue by Threak** [piejanssens/premiumizer#167]
Hello,

I tried to install premiumizer from master branch and get an error:
ERROR: Could not find a version that matches python-socketio<4,==4.0.0,>=2.1.0

Flask_socketio 3.3.2 requires python-socketio <4
https://github.com/miguelgrinberg/Flask-SocketIO/blob/v3.3.2/setup.py#L29

However, premiumizer has python-socketio == 4 as dependency
https://github.com/piejanssens/premiumizer/blob/master/requirements.txt#L20

**Comment by piejanssens** [comment]
@neox387 Please review this https://github.com/piejanssens/premiumizer/commit/e32fc5d1cf857bc1e0005b929ae46ffc01ccb304#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by neox387** [comment]
Well I asked the question over there
https://github.com/miguelgrinberg/Flask-SocketIO/issues/929

Im running it with python-socketio 4 np lol, he put in <4 for some reason tought I guess..

**Comment by neox387** [comment]
#168 

it's back on 3.1.2 till he fixes.
