### ISSUE TITLE
Zombie process because SIGINT (Ctrl-C) and SIGTERM (kill) not handled

### ISSUE THREAD

**Issue by msheakoski** [piejanssens/premiumizer#176]
If I start the premiumizer docker container in the foreground and press Ctrl-C, it should gracefully stop whatever it is currently doing and shut down. Currently, the only way to kill it is with `docker kill <container_id>`.

This also causes issues when trying to run the premiumizer docker container as a systemd service in the background because it refuses to die, which blocks both restarting the service, and rebooting the OS.

Both SIGINT (Ctrl-C) and SIGTERM (kill / docker stop) should signal to premiumizer that it is time to stop whatever it is doing, clean up, and maybe remember what task it was in the middle of so it can resume when it starts back up again.

**Comment by neox387** [comment]
try again after merge #177

**Comment by msheakoski** [comment]
Thank you, @neox387! It looks like the PR was merged but the Docker container is still an old version from 25 days ago. Is the Docker image building a manual process?

**Comment by neox387** [comment]
Donno @piejanssens

**Comment by piejanssens** [comment]
The issue in our automated builds is fixed. You should see a new build in the registry.
