### ISSUE TITLE
Make outward-facing API

### ISSUE THREAD

**Issue by haboutnnah** [piejanssens/premiumizer#178]
So that it can be added to tools such as NZB360, it would be nice if you could add an outward-facing api of Premiumizer.

**Comment by neox387** [comment]
I have looked at it in the past but seems rather complicated, if someone can make it go ahead xP

**Comment by piejanssens** [comment]
@haboutnnah Why don't you use nzbget for that?

**Comment by haboutnnah** [comment]
higher retention

**Comment by piejanssens** [comment]
There is a difference in retention using de web downloader as opposed to the usenet credentials from the same Premiumize account? 😲
