### ISSUE TITLE
Bundle the docker image with vpn?

### ISSUE THREAD

**Issue by GOvEy1nw** [piejanssens/premiumizer#179]
Hey, I've installed the docker image on my Synology NAS and it is working a treat with Sonarr & Jackett. However, I'm a privacy concious guy & would love if premiumizer could be bundled with an optional VPN in the docker image. Is this possible at all?

**Comment by neox387** [comment]
No idea howto do this :) can't you VPN on router or Synology? But then everything instead of 1 Docker image would go trough :)

**Comment by piejanssens** [comment]
This will never happen. I'm sure there are solutions to use a VPN client container to provide network access to another container.
