### ISSUE TITLE
Very Large Memory Leak

### ISSUE THREAD

**Issue by haboutnnah** [piejanssens/premiumizer#183]
So, I was wondering why my RAM usage was mad high at idle (75odd percent).

I opened RamMap from Microsoft, sorted by memory usage of 0, and found about 80 percent of my scroll bar were python instances. One by one, I close every app I have that relates to python, and when I closed this one it dropped to 60% (of my 16GB)!  

This means the app is holding on to false handles.

This is on Windows 10.

**Comment by neox387** [comment]
Weird, can you reproduce this? Is it after running a long time?

I got mine running for days on a Windows 10 vm shared with sonarr/radarr and jdownloader and have only 43% of 3gb ram usage =)

Opend the rammap where can you all the instances?

**Comment by haboutnnah** [comment]
there aren't instances of python live, just that the program holds on to the handles so the memory is freed but not the memory mappings. 
was after about 3 days.
I now have a script that restarts it every 4 hours

**Comment by neox387** [comment]
tried to find something with Pympler but don't see anything weird

**Comment by piejanssens** [comment]
I have no apparent memory leak issues in Docker either...

**Comment by piejanssens** [comment]
Confirmed

<img width="799" alt="Schermafbeelding 2019-07-26 om 08 04 22" src="https://user-images.githubusercontent.com/829098/61929723-108d1e00-af7c-11e9-8376-e2c995c35424.png">

**Comment by neox387** [comment]
still wtf 4.64GB of ram that is not right =D

you use aira2 ?

**Comment by neox387** [comment]
I am not seeing anything .. thought it might be in the while loops for get_download_stats seems python might hold on to everything so after the while loop stats it gets free but don't see it happening..

you could test with 
import gc

and at the end before the while loop starts again
gc.collect()

**Comment by piejanssens** [comment]
Using built in downloader.

**Comment by neox387** [comment]
Would make more sense if this came from pysmartdl..? 

@haboutnnah where you also using the built in Downloader?
