### ISSUE TITLE
Reverse Proxy with flask_behind_proxy not working

### ISSUE THREAD

**Issue by neox387** [piejanssens/premiumizer#186]
<script src="{{ url_for('static',…

in the html files is not returning the /location it should..

asked the dev in comparision with flask-reverse-proxy what needs to be changed or why it isn't doing this..

but anyway why replace the lib ? =D

**Comment by piejanssens** [comment]
It wasn't working for me. Https was being redirected to http. It seems to be working now (for me).
Where do you see problems for the moment exactly?

**Comment by neox387** [comment]
I'm, using myurl/prem for premiumizer, myurl/tv for sonarr etc

With flask reverse proxy things like:
<script src="{{ url_for('static', filename='js/bootstrap-switch.min.js') }}?v=4"></script>

Return as myurl/prem/static/js/bootstrap-switch.min.js'

But with flask behind proxy it's returning as root so myurl/static/js/bootstrap-switch.min.js so it obviously doesn't find anything

**Comment by neox387** [comment]
Sonarr for example does have a url base setting for reverse proxy, I have it set to /tv

Maybe we need a setting like this, just wasn't needed with flask reverse proxy because it seemed to do this by itself based on the url you entered.. 

I have no probs with http everything I enter even with http returns as https =D but that's nginx settings..

**Comment by neox387** [comment]
so are you using it with location / { or a custom one cause that is where to problem is at least the part where url_for isn't adjusting to this.

**Comment by piejanssens** [comment]
My reverse proxy is subdomain based, one sub per service.

**Comment by neox387** [comment]
I see donno if it has benefits.. never tough of it just seems easier to change trailing / instead of subdomain.

Anyway gonna try explain to dev, I think it's just not build into flask-behind-proxy so we would need the option to use a url base..

**Comment by neox387** [comment]
Found the issue. flask-behind-proxy has no support for
proxy_set_header X-Script-Name

this makes it work in flask reverse proxy without setting an url base or something in flask itself

**Comment by neox387** [comment]
Well I fixed it myself, also added an option in settings to use URL base without needing to use proxy_set_header X-Script-Name in nginx, this is still supported however if user sets it there.

**Comment by piejanssens** [comment]
Thanks, but I would prefer something that just works for both type of reverse proxies without requiring any config. I will reverse back to flask-reverse-proxy if necessary.

**Comment by neox387** [comment]
Well it will work like flask behind proxy and you can leave URL base blank to not use it

**Comment by neox387** [comment]
And config is even easyer I removed
proxy_set_header X-Script-Name /prem from nginx and used the url base option in premiumizer to use /prem

Then it works the same as sonarr/radarr does it =)
