### ISSUE TITLE
QNAP update not possible

### ISSUE THREAD

**Issue by theincogtion** [piejanssens/premiumizer#193]
Source
https://www.qnapclub.eu/en/qpkg/696
(the version looks outdated)

In the log I get:

06-17 19:21:37: ERROR : Update failed: could not git fetch: /share/CE_CACHEDEV1_DATA/.qpkg/QPremiumizer/premiumizer

in the debug log:

> 06-17 19:25:09       root                                     : DEBUG    : DEBUG Logfile Initialized
06-17 19:25:09       root                                     : INFO     : Running at /share/CE_CACHEDEV1_DATA/.qpkg/QPremiumizer/premiumizer
06-17 19:25:09       root                                     : DEBUG    : Initializing config
06-17 19:25:09       root                                     : DEBUG    : Initializing config complete
06-17 19:25:09       root                                     : DEBUG    : Initializing Flask
06-17 19:25:09       engineio.server                          : INFO     : Server initialized for gevent.
06-17 19:25:09       root                                     : DEBUG    : Initializing Flask complete
06-17 19:25:09       root                                     : DEBUG    : Initializing Database
06-17 19:25:09       root                                     : DEBUG    : Initializing Database complete
06-17 19:25:09       root                                     : INFO     : Starting server on 0.0.0.0:15000 
06-17 19:25:09       root                                     : DEBUG    : def load_tasks started
06-17 19:25:09       socketio                                 : INFO     : emitting event "update_task" to all [/]
06-17 19:25:09       apscheduler.scheduler                    : INFO     : Scheduler started
06-17 19:25:09       apscheduler.scheduler                    : INFO     : Added job "update" to job store "default"
06-17 19:25:09       apscheduler.scheduler                    : INFO     : Added job "check_update" to job store "default"
06-17 19:25:09       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
06-17 19:25:09       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-06-17 19:25:10.671876+02:00 (in 0.956971 seconds)
06-17 19:25:10       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
06-17 19:25:10       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-06-17 19:25:11.671876+02:00 (in 0.997946 seconds)
06-17 19:25:10       apscheduler.executors.default            : INFO     : Running job "check_update (trigger: interval[0:00:01], next run at: 2019-06-17 19:25:11 CEST)" (scheduled at 2019-06-17 19:25:10.671876+02:00)
06-17 19:25:10       root                                     : DEBUG    : def check_update started
06-17 19:25:10       root                                     : ERROR    : **Update failed: could not git fetch**: /share/CE_CACHEDEV1_DATA/.qpkg/QPremiumizer/premiumizer
06-17 19:25:10       apscheduler.executors.default            : INFO     : Job "check_update (trigger: interval[6:00:00], next run at: 2019-06-18 01:25:10 CEST)" executed successfully
06-17 19:25:10       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run

**Comment by neox387** [comment]
Start with premiumizer.py --docker it will skip update check
