### ISSUE TITLE
Task title needs to be updated as it changes

### ISSUE THREAD

**Issue by piejanssens** [piejanssens/premiumizer#195]
Otherwise premiumizer shows `magnetxturnbtih02EDCE532DF8B6...` and will eventually end up like that in a folder name while the real title is already pieced together and showing in premiumize.me.

**Comment by neox387** [comment]
Never had this.. It is from a magnet file that doesn't have &dn= in the link for the name?

**Comment by piejanssens** [comment]
Indeed
