### ISSUE TITLE
How to pause downloads from commandline?

### ISSUE THREAD

**Issue by Appyx** [piejanssens/premiumizer#200]
I want to stop the running download per commandline to automate the sleep-wake cycle of my machine. Is this possible?

I sleep my system over ssh and wake it with wol (keeping it alive with caffeinate).

Other things I noticed...
When using JD and the download gets interrupted manually via my.jd.org, then premiumizer marks the download as failed. Communication from JD to Premiumizer seems to be pretty unstable at times. 
For instance it would be cool if the state of JD would be reflected in Premiumizer when pausing downloads.

**Comment by neox387** [comment]
Not gonna be able to interact with the python script trough command line.

You can stop downloads on home page? Or just shutdown premiumizer should check downloads that where running before.

But ye if u interrupted JD while premiumizer is downloading it will fail. Only way is to pauze/stop from premiumizer itself

**Comment by Appyx** [comment]
Ok thx.
Maybe I will implement webhooks for remote controlling Premiumizer...

Is the state reporting from JD limited due to the python-jd-api or is it just not inplemented?

**Comment by neox387** [comment]
Is possible but that would require alot more code probably xD

**Comment by neox387** [comment]
And ye some api would be nice I guess to for example be able to integrate in sonarr etc #178
