### ISSUE TITLE
Folder Names are cut off

### ISSUE THREAD

**Issue by mooneye14** [piejanssens/premiumizer#203]
When premiumizer is pulling folder and file names and initializing downloads, it is cutting off folder names, which also causes the auto delete option to fail because it's trying to delete something with a different name. Actual movie files are fine, just the folders.

**Comment by neox387** [comment]
donno... some os limit to characters for folder name or something ?

**Comment by mooneye14** [comment]
I don't think so.. but maybe? It's a synology running the container and it's an intermittent thing. Longer folder names will be complete while shorter ones won't. I thought it might be an escape character? The folders first appearance in the log was incorrect compared to what was in Premiumize cloud. I didn't have debug logging on but can try that soon.

**Comment by piejanssens** [comment]
Debug logs might be helpful indeed.

**Comment by mooneye14** [comment]
Premiumize is the one doing this. Mizer is just honoring that name.
