### ISSUE TITLE
Delete not working

### ISSUE THREAD

**Issue by kungfoolfighting** [piejanssens/premiumizer#217]
I am running premiumizer in a docker container.
Currently, pressing the trashcan icon does not delete files anymore. Simply nothing happens.

**Comment by neox387** [comment]
Guess you using proxy. 

Full in new option in settings global its for security reasons:
Custom host and domain

**Comment by kungfoolfighting** [comment]
Thx for the reply. What exactly do I have to enter there? I am using an nginx reverse proxy from the http://homeserver/premiumizer url to homeserver:portnumber I only access the website in my LAN.

**Comment by neox387** [comment]
I think homeserver however it might not work because it expects something like homeserver.example.net and not just the hostname need to change this

You can try to put it directly in settings.cfg under custom_domain=

Or instead of hostname it will work without the setting and if you use the ip address

**Comment by kungfoolfighting** [comment]
Thanks a lot, that did the trick. The inability of the UI to accept just "homeserver" was what prevented it from working initially.

**Comment by neox387** [comment]
Ye I'll fix it later

**Comment by neox387** [comment]
and fixed with #219

**Comment by piejanssens** [comment]
@kungfoolfighting Please test and close.

**Comment by JRDevo** [comment]
Hi :)

I have premiumizer on both Windows and Dietpi (python 3.7.0), no proxies.

Both installations are not deleting nor downloading. Clicking the delete button doesn't show any reaction.

[PI premiumizerDEBUG.log](https://github.com/piejanssens/premiumizer/files/3475867/PI.premiumizerDEBUG.log)

**Comment by neox387** [comment]
Gonna be like above fill in custom hostname and/or domain in settings
