### ISSUE TITLE
Unable to set 2 level deep subdirectory

### ISSUE THREAD

**Issue by breakmylegs** [piejanssens/premiumizer#229]
Hi,

When I try to set the directory on a category to anything more than one directory deep the setting doesn’t get saved e.g. /tv/TV2 which just saves as /tv. 
I tried updating the config file directly and restarting but the same thing happened

**Comment by neox387** [comment]
Weird, this is not on windows right? Check log or try devog mode if log gives some error

**Comment by breakmylegs** [comment]
It’s the docker image running on Ubuntu. 
All the logs show are 
09-19 21:33:10: INFO : Settings saved, reloading configuration
09-19 21:33:10: INFO : Watchdir is enabled at: /blackhole

**Comment by neox387** [comment]
OK so no error so even if you put /tv/TV2 on restarted it changes to just /tv? Weird I'm guessing it has something to do with Docker donno does the folder TV2 exists then or did you create it yourself

**Comment by breakmylegs** [comment]
Even with debug logs on there is no mention of it trying to do anything with TV2. Its as if it ignores it. 
TV2 is mount inside the tv directory that goes to another network drive. The other applications, such as Plex, can read and write to it

**Comment by breakmylegs** [comment]
I also just created a brand new category there called test and gave it the directory /test/test. 
It only saved with /test
