### ISSUE TITLE
Security settings 

### ISSUE THREAD

**Issue by jbwolf82** [piejanssens/premiumizer#232]
Premiumizer has been working for some time now. But now chrome will not let me into it. Is there certain settings I should check?

**Comment by neox387** [comment]
Still working here on chrome, firewall?

**Comment by jbwolf82** [comment]
Man I'm not sure what i did wrong. I installed a cleaning program and not sure if that has something to do with it.

**Comment by jbwolf82** [comment]
I uninstalled and reinstalled and all is good.
