### ISSUE TITLE
Torrents not auto downloading with category

### ISSUE THREAD

**Issue by Shruikand** [piejanssens/premiumizer#236]
Hey,

I've set up the categories, and when my Sonarr adds a magnet link, Premiumizer picks it up, but it's stuck at 'Downloading', and not doing anything.

When I change the category to the same category (or other category), it starts. 

It worked when I first installed it, but after a restart of my system it stopped working.

Any idea's?

**Comment by neox387** [comment]
Enable debug mode restart and see if there is some error in log..

**Comment by CaptainMoody** [comment]
I may be having the same issue.
I only started using Premiumize yesterday but my first scheduled download (via Sonarr) failed.
The error in the debug log is here:
`10-29 08:43:06       apscheduler.executors.downloads          : ERROR    : Job "FILENAME.mkv (trigger: date[2019-10-29 08:43:06 GMT], next run at: 2019-10-29 08:43:06 GMT)" raised an exception
Traceback (most recent call last):
  File "/home/chris/Premiumizer/env/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/chris/Premiumizer/premiumizer/premiumizer.py", line 1440, in download_task
    failed = download_process()
  File "/home/chris/Premiumizer/premiumizer/premiumizer.py", line 1424, in download_process
    process_dir(dir_content, greenlet.task.dldir)
  File "/home/chris/Premiumizer/premiumizer/premiumizer.py", line 1383, in process_dir
    if x['link'].lower().endswith(tuple(greenlet.task.dlext)):
TypeError: 'NoneType' object is not iterable`

**Comment by CaptainMoody** [comment]
This is also happening with nzb files:

`10-30 08:34:38       apscheduler.executors.downloads          : ERROR    : Job "Emergence.S01E05.1080p.WEB.H264-METCON.nzb (trigger: date[2019-10-30 08:34:38 GMT], next run at: 2019-10-30 08:34:38 GMT)" raised an exception
Traceback (most recent call last):
  File "/home/chris/Premiumizer/env/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/chris/Premiumizer/premiumizer/premiumizer.py", line 1440, in download_task
    failed = download_process()
  File "/home/chris/Premiumizer/premiumizer/premiumizer.py", line 1408, in download_process
    if not greenlet.task.dldir.endswith(name):
AttributeError: 'NoneType' object has no attribute 'endswith'`

**Comment by neox387** [comment]
@CaptainMoody this is something else, did you set a download directory in settings - Downloader - general? Also need to delete and re add the download for it to change

**Comment by CaptainMoody** [comment]
@neox387 
I have two folders setup on my server:
Watch folder - /media/StorageA/Premiumizer/InBox
Download Location - /media/StorageA/Premiumizer/Watch

NZBs & torrents are successfully processed by Sonarr and Premiumizer, it is just the download that never starts.
If I manually add a torrent or NZB the download does take place

**Comment by neox387** [comment]
And are you using blacklist extension? Normal if you add manually and assign category same as sonarr puts it the download process would be the same

**Comment by CaptainMoody** [comment]
Blacklist Ext in categories is all set to off

**Comment by neox387** [comment]
Let sonarr put it in /media/StorageA/Premiumizer/Watch/tv then it should start with the category tv

**Comment by CaptainMoody** [comment]
Thanks for your help @neox387.
Now I have categories set up correctly everything is working as it should.

**Comment by neox387** [comment]
Donno Google run program at startup Linux or something, I run on Windows :)
