### ISSUE TITLE
Premiumizer stops working

### ISSUE THREAD

**Issue by Tscherno** [piejanssens/premiumizer#238]
Everything worked fine until some point. From there on Premiumizer is stuck "Loading download tasks". Debug logs doesn't show much:
11-24 12:50:27       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
11-24 12:50:27       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-11-24 12:50:28.244098+01:00 (in 0.999104 seconds)
11-24 12:50:27       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2019-11-24 12:50:28 CET)" (scheduled at 2019-11-24 12:50:27.244098+01:00)
11-24 12:50:27       root                                     : DEBUG    : def update started
11-24 12:50:27       root                                     : DEBUG    : def prem_connection started
11-24 12:50:27       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
11-24 12:50:27       root                                     : DEBUG    : def parse_task started
11-24 12:50:27       root                                     : DEBUG    : def get_task started
11-24 12:50:27       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2019-11-24 12:50:28 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "premiumizer.py", line 1227, in update
    idle = parse_tasks(transfers)
  File "premiumizer.py", line 1310, in parse_tasks
    speed=speed + ' --- ', eta=eta, folder_id=folder_id, file_id=file_id)
UnboundLocalError: local variable 'eta' referenced before assignment
11-24 12:50:27       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
11-24 12:50:27       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request

**Comment by neox387** [comment]
I think you are running an old version based on these line numbers
File "premiumizer.py", line 1227, in update
idle = parse_tasks(transfers)
File "premiumizer.py", line 1310, in parse_tasks
