### ISSUE TITLE
Unable to have Premiumizer start at boot Linux 64bit

### ISSUE THREAD

**Issue by chest069** [piejanssens/premiumizer#239]
Hello,

I was able to successfully install, run and setup Premiumizer on Linux 64bit but I unable to get it to autostart at boot. Can you help?

This is what I have to do everytime to get it to run after I log in:

virtualenv -p /usr/bin/python3 env (this is what I have to put in on my system) vs virtualenv -p /usr/local/bin/python3 env (which is what the instructions say)
source env/bin/activate
pip install -r requirements.txt
python premiumizer/premiumizer.py (It then runs and I can goto the web page)

So how do I get this to run at boot automatically? Thanks for any help.

**Comment by neox387** [comment]
well that is not normal, i am however not running linux or trough virtualenv anymore.
pip install -r requirements.txt doesnt need be run everything for sure.

I would say google howto boot stuff at start on linux

**Comment by chest069** [comment]
ok thanks
