### ISSUE TITLE
Only for premiumize.me v cloud torrents, nzb

### ISSUE THREAD

**Issue by siliconhippy** [piejanssens/premiumizer#242]
Hi !

Noob question. Is this package only for premiumize.me, or will it work independently with the usual cloud torrents and nzbToMedia?

Does this tool work with Plex Server or Emby?

**Comment by chest069** [comment]
Basically, I would say yes. I use it with the service but I am able to set it up with things like Sonarr and Radarr. They grab what I want and it gets me the files. It's kind of a downloader and middleman all in one. Hope this made sense.

**Comment by siliconhippy** [comment]
Thanks, impressive !
