### ISSUE TITLE
Can't run container in Docker

### ISSUE THREAD

**Issue by robbobloke** [piejanssens/premiumizer#243]
I have raspberry pi4 running raspbian buster. When trying to run premuimizer in docker it doesn't run and immediately exits upon start.
Checking the logs I get the following error:
`standard_init_linux.go:211: exec user process caused "exec format error`
Is there something I'm doing wrong? Thanks for any help.

**Comment by tuefekci** [comment]
https://github.com/piejanssens/premiumizer/issues/255#issuecomment-636320196

**Comment by piejanssens** [comment]
@alinefr Could you have a look please? Can this be introduced by your change on the entry file?

**Comment by alinefr** [comment]
This is because the hosted container was not built for armv7, maybe only amd64? There is a way to auto build for at least armv7, arm64 & amd64 with buildx. I'm not sure if Docker Hub does it or if we would need a CI like Travis. I'll see.

For now, could you guys try my alinefr/premiumizer:latest?

**Comment by piejanssens** [comment]
https://hub.docker.com/r/ckulka/multi-arch-example

**Comment by alinefr** [comment]
> https://hub.docker.com/r/ckulka/multi-arch-example

This is very cool! 
I'm writing additional Dockerfile's for arm32v7 & arm64v8 based on this example and PR it back when I get it working.

**Comment by piejanssens** [comment]
Try again please. Check the updated readme instructions. Close if resolved.

**Comment by robbobloke** [comment]
works perfect now on Pi4, many thanks!!
