### ISSUE TITLE
Reverse Proxy not working

### ISSUE THREAD

**Issue by GOvEy1nw** [piejanssens/premiumizer#244]
I believe I had this working before an update, but now I can't get it to work.

I'm on a Synology Nas, and I'm running Premiumizer, Sonarr, Radarr etc through a VPN container, and also an NGINX container in order to be able to use the reverse proxy.

I have it working perfectly fine with Sonarr, Radarr etc, but for some reason Premiumizer no longer works. When I try to visit it via my url it redirects to the following: `https://premiumizer:4242/login?next=%2F`

my url is set up as `premiumizer.myurl.xyz`, I've also tried setting this in the 'custom host' settings in the premiumizer app, but no luck.

I can access it fine via `192.168.1.4:4242` but it's just the reverse proxy doesn't work. I'm struggling to figure out why this is the case since I have 4 other containers setup the exact same way that work fine via reverse proxy.

**Comment by neox387** [comment]
think you gonna have to check nginx config, because if you browse to premiumizer.myurl.xyz and it returns without myurl.xyz I think nginx does this ? I have the following config in nginx

I use it with myurl.xyz/prem instead of prem.myurl.xyz tough

    location /prem {
        proxy_pass http://192.168.0.101:8903;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
