### ISSUE TITLE
Settings for Default cat not sticking & remove_cloud_delay

### ISSUE THREAD

**Issue by mooneye14** [piejanssens/premiumizer#249]
Running in Docker on DSM. settings.cfg excerpts below:

download_all = 1
...
cat_name[6] = default
cat_dir[6] = /downloads
cat_ext[6] = _exe,nfo,txt_ 
cat_ext_blacklist[6]= _1_
cat_delsample[6] = 0
cat_nzbtomedia[6] = 

I used to have 'download_all' On and be able to Delete Sample and whitelist Extensions. Updated last week and now settings as emph above will not stay in settings.cfg even if I manually type them into the file. I can however change cat_delsample[6] to 1 in the .cfg manually, but not in the GUI. 

Also, the remove_cloud_delay is removing files instantly even though I have it set to 12. Does that rely on TZ and system clock? I am (GMT-06:00) and TZ EV was set to America/Chicago.

I am working on getting more backend automation to take care of this with Sonarr, etc but what I used to do was 1. Click a magnet link on rarbg. 2. Browser set to handle all magnet links with Premiumize 3. Files show up in PZ 4. Download all w/ Default on Premiumizer would dl files to NAS in an Inbox type folder. Plex TV and Movie libraries both were watching Inbox folder and did a decent job of figuring which went to what library. 6. Remove from cloud delay allowed me to download copy to phone if I'm away from home doing this and about to board a plane. 7. Sort files later or delete if watched by hand.

**Comment by neox387** [comment]
just tested remove_cloud_delay and it is working here. it takes current time and just ads the hours so tz etc shouldnt be a problem:
next_run_time=(datetime.now() + timedelta(hours=cfg.remove_cloud_delay))

after download task should say:
Waiting to delete
Speed: Size: ETA: Deleting from cloud in: 0:00:18

**Comment by neox387** [comment]
fixed default cat settings not saving in PR

**Comment by mooneye14** [comment]
All my EV are set as this, synology DSM also set to Central Time GMT -06:00 and synced to time.google.com. Syno doesn't need to have its own NTP turned on does it?
``` {
         "key" : "PUID",
         "value" : "1024"
      },
      {
         "key" : "PGID",
         "value" : "100"
      },
      {
         "key" : "TZ",
         "value" : "America/Chicago"
      }```

**Comment by neox387** [comment]
mm guess it could be a problem after all would have to look into this some more

**Comment by mooneye14** [comment]
remove_cloud_delay doesn't work if seed private tracker is also on. I thought it was timezone issues bc all my logs were in UTC. Turns out tzdata apk not loaded into Alpine was causing TZ to be useless. Submitted PR to fix.
