### ISSUE TITLE
Bandwith limitation internal downloader

### ISSUE THREAD

**Issue by speedy80** [piejanssens/premiumizer#25]
First of all: thank you for this great software!

Would it be possible to add an option to limit the bandwith used for the internal downloader? I share the bandwith (home office) and a imitation would be very useful.

**Comment by neox387** [comment]
This is implemented in the downloader we use: pysmartdl, but it's not active so I guess there is a problem why the developer did this, but sadly pysmartdl isn't actively developed anymore & there aren't any good alternatives.

so probbably not. 

It is possible with Jdownloader however, recently implemented Jdownloader trough my Jdownloader api, & there you can limit bandwith or do multipart download for faster downloads, wich allso doesn't work good on pysmartdl..

**Comment by speedy80** [comment]
Tried Jdownloader. Mostly it works fine. 
With some files I have an issue where Jdownloader shows an error (try restarting this link (plugin outdated?). Files are shown in Jdownloader but size is always 0B.
I can manualy download the files. The files not working are always from a link similar to this one:
http://dt63.energycdn.com/zip/1Xuv4qDYg9mmcqruQdA3Uw/1460056716/3029516/321a9fbf99a91df1ab711a60b89f74e7130c9847/"the file here"

**Comment by neox387** [comment]
I'm using jdownloader 2 beta not 1 donno if that's still available, it supports bunch of file hosters including premiumize.me allso where u can input your account. but shouldn't be needed for direct links, but the one u linkt above is a zip of a torrent I guess..

anyway seems not related to premiumizer..

**Comment by neox387** [comment]
Ok, I have seen this problem on some downloads as well:
 

> 
try restarting this link (plugin outdated?)

opening the url of the link in browser results in 404 Not Found

trying to find the problem but I don't see it :/

**Comment by neox387** [comment]
Found it in my jd Api code will be fixed soon

**Comment by neox387** [comment]
can close this, opened issue here #43

**Comment by neox387** [comment]
@speedy80 Do u still have problems ? internal downloader should work now with a speed limit that you can set on the options page, I still recommend using Jdownloader 2 however :)
