### ISSUE TITLE
NextUP Setting

### ISSUE THREAD

**Issue by lance77tour** [piejanssens/premiumizer#250]
Where is the location for NextUp? I've used premiumizer for months and have yet to see any pop-up as is mentioned like Up Next. I've even searched Google to find very few links regarding NextUp.

Am I missing something?

![Capture](https://user-images.githubusercontent.com/57505743/77869767-4c603d80-7205-11ea-97f1-145ad613ded7.PNG)

**Comment by piejanssens** [comment]
This has nothing to do with this Premiumizer, which only facilitates downloading your cloud files.
