### ISSUE TITLE
Unable to start Premiumizer service

### ISSUE THREAD

**Issue by ash718** [piejanssens/premiumizer#252]
After installation using exe file windows 10.. i go into services to change the logon to my admin account. after doing so premiumizer service wont start. i get a popup stating that " windows cannot start the premiumizer service on local computer. the service did not return an error." please help.

**Comment by neox387** [comment]
You could enable the log to see what error you get starting a service:
in the install folder eg. C:\Premiumizer\Installer you have nssm.exe

open command prompt
cd C:\Premiumizer\Installer
nssm.exe edit Premiumizer

then in IO - output put a path to a file eg. C:\Premiumizer\Installer\error.txt


Could also try to start it manually:
open command prompt
C:\Premiumizer\Python\python.exe C:\Premiumizer\Premiumizer\premiumizer\premiumizer.py

**Comment by ash718** [comment]
thanks for responding, after using cmd to stop/start/restart premiumizer. it stops succesfully however when trying to start error is - the service did not start due to logon failure. what would you suggest for a fix?

**Comment by neox387** [comment]
this would mean log on as your username or password is wrong.

**Comment by ash718** [comment]
its not possible, i even created a new admin account and checked it in services.msc with other services and i was able to change the Logon service for them. its weird, now on cmd it shows this -
Premiumizer: START: The operation completed successfully.
however in services it still shows paused. when trying to connect premiumizer to 127.0.0.1:5000 it doesnt load.

**Comment by ash718** [comment]
![premiumizer error -1](https://user-images.githubusercontent.com/63767565/79582149-615c1e00-8099-11ea-9ddb-42ab96b1d5c4.jpg)

**Comment by neox387** [comment]
you tried starting normal without service to see if it works?
Could also try to start it manually:
open command prompt
C:\Premiumizer\Python\python.exe C:\Premiumizer\Premiumizer\premiumizer\premiumizer.py

**Comment by ash718** [comment]
do i input this as 2 separate commands or all in 1 shot? forgive me but i have zero experience in cmd.
also im running cmd in Admin mode.

**Comment by ash718** [comment]
yes i tried starting it normally without service and got the same thing initially.

**Comment by ash718** [comment]
![error -2](https://user-images.githubusercontent.com/63767565/79584455-6a9aba00-809c-11ea-989f-9e7a4fea8bb1.jpg)

**Comment by neox387** [comment]
well something in the install got fuckt, python and git are not portable anymore so you probably already had them installed

or you uninstall premiumizer, git and python and install premiumizer again, or fix it manualy.

you probably don't have anything in C:\Premiumizer\Python now ? if you do:
C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt
else an try
python install -r C:\Premiumizer\Premiumizer\requirements.txt

but ye prob easiest to uninstall them all and let installer do it again

**Comment by ash718** [comment]
![error3](https://user-images.githubusercontent.com/63767565/79585964-856e2e00-809e-11ea-810c-359ca526f5bc.jpg)

**Comment by ash718** [comment]
the installer keeps giving me these errors
![Premiumizer error1](https://user-images.githubusercontent.com/63767565/79586046-a040a280-809e-11ea-95e9-f749ee316856.jpg)
![Premiumizer error2jpg](https://user-images.githubusercontent.com/63767565/79586048-a040a280-809e-11ea-8326-d8b323c93ba6.png)
![Premiumizer error3](https://user-images.githubusercontent.com/63767565/79586049-a040a280-809e-11ea-8e95-522b3a56817b.jpg)
![Premiumizer error4](https://user-images.githubusercontent.com/63767565/79586050-a0d93900-809e-11ea-9a0f-6dce29e6316f.jpg)

**Comment by ash718** [comment]
this is day 5 trying to figure this out. with day one looking exactly like these errors.

**Comment by ash718** [comment]
let me ask you, im trying to run sonarr with premiumize strictly for torrents. can i do this any other way easily other than using premiumizer?

**Comment by ash718** [comment]
i uninstalled and reinstalled it a few times and it installed finally with no errors. However im still not able to get services to run.

**Comment by neox387** [comment]
well above in screenshot you had it on C on others you installing to Z ? it literally says it cant find the files.
if you uninstall and reinstall, also repair/uninstall python and git first

**Comment by ash718** [comment]
i wanted to see if changing drives would make a difference but it didn't, so i ended up getting it installed back on the C drive without any errors. but its stilll not starting in the services page.

**Comment by neox387** [comment]
well if no error like above then hopefully it installed correctly then you should be able to start it manually.

but if it says above error like no module named bencode then it didnt install correctly like i said above:
C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt

**Comment by ash718** [comment]
![error4](https://user-images.githubusercontent.com/63767565/79600642-7cd52200-80b5-11ea-85aa-e459cca79694.jpg)

**Comment by ash718** [comment]
![error5](https://user-images.githubusercontent.com/63767565/79600661-852d5d00-80b5-11ea-98bd-7ace80a55079.png)
![error6](https://user-images.githubusercontent.com/63767565/79600663-852d5d00-80b5-11ea-9d1d-34e3f463e62f.png)

**Comment by ash718** [comment]
this is what i got after inputting the command you suggested

**Comment by neox387** [comment]
OK well think you need to wait for my pr to be merged that gevent 1.4. 0 doesn't want to install new one has 1.5.0

You could make a copy of the requirement.txt edit gevent==1.5.0 and try installing that one if you don't wanna wait.

If you edit the main file future updates gonna fail..

**Comment by ash718** [comment]
ok, what do i need to edit in the file?

**Comment by neox387** [comment]
gevent==1.5.0

Instead of
gevent==1.4.0

**Comment by ash718** [comment]
same result...

**Comment by ash718** [comment]
![error7](https://user-images.githubusercontent.com/63767565/79601963-a727df00-80b7-11ea-969c-5540e0ca3154.png)
![error8](https://user-images.githubusercontent.com/63767565/79601964-a7c07580-80b7-11ea-8c28-aeb81e6cbf6b.png)

**Comment by ash718** [comment]
Do you have a fix?

**Comment by eks4x4** [comment]
I was facing the exact same issues as @ash718.
So I followed the troubleshooting steps in this thread,  there is a line at the bottom of the log:

`distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`

![image](https://user-images.githubusercontent.com/63938103/79687548-d98f2480-81fc-11ea-8704-66fe3eee1bf8.png)

So I installed [Microsoft Visual C++](https://visualstudio.microsoft.com/visual-cpp-build-tools/)

re-ran (with requirements.txt unmodified  still using gevent==1.4.0 ):
C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt

And that succeed to install everything without any issue.
Restarted the premiumizer service, and it came up fine on localhost:5000

Hope this helps, GL

**Comment by neox387** [comment]
Ye im gonna update the installer to include the vc++ build tools

**Comment by neox387** [comment]
New installer is up that has visual c included, again if you want to reinstall best to remove python/git first and then premiumizer else it gets a bit messy
https://github.com/neox387/PremiumizerInstaller/releases

**Comment by ash718** [comment]
says download failed: file not found (404)

**Comment by ash718** [comment]
> 
> 
> I was facing the exact same issues as @ash718.
> So I followed the troubleshooting steps in this thread, there is a line at the bottom of the log:
> 
> `distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`
> 
> ![image](https://user-images.githubusercontent.com/63938103/79687548-d98f2480-81fc-11ea-8704-66fe3eee1bf8.png)
> 
> So I installed [Microsoft Visual C++](https://visualstudio.microsoft.com/visual-cpp-build-tools/)
> 
> re-ran (with requirements.txt unmodified still using gevent==1.4.0 ):
> C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt
> 
> And that succeed to install everything without any issue.
> Restarted the premiumizer service, and it came up fine on localhost:5000
> 
> Hope this helps, GL

Thank you very much. i only wished that i didn't totally uninstall premiumizer to install the new version before trying your method first. The new one wont install at all and i cant try your method. lol but im glad you got it to work.

**Comment by ash718** [comment]
v1.0 installer isnt working. getting a download failed message when trying to install ..  : /

**Comment by ash718** [comment]
if you could fix the installer by tonight i would really appreciate it @neox387

**Comment by ash718** [comment]
Hate to sound like a pest, but do you have a fixed installer ready?

**Comment by neox387** [comment]
Woops I see what's wrong Sorry, I Test my dev version and changed to much back to piejanssens xD

**Comment by ash718** [comment]
It's cool, just let me know when i can re download the fixed installer. Thanks

**Comment by neox387** [comment]
alright just updated the .exe on the 1.0 release try again plz .D
https://github.com/neox387/PremiumizerInstaller/releases

**Comment by ash718** [comment]
Installed perfectly and its finally working. Thank you very much. I Appreciate it

**Comment by ash718** [comment]
would you know how to set this up with sonarr to automate torrents for Plex?

**Comment by neox387** [comment]
Sonarr:
- settings - Download Client - add - torrent and or usenet Blackhole
Torrent folder c:\watchdir\tv (same in radarr/couchpotato but with c:\watchdir\movie)
You could use watch folder c:\downloads\premiumizer\tv I dont use this I use nzbtomedia
Save Magnet files enabled



premiumizer:
- settings - Premiumize.me
insert api key from account page on premiumize.me website


- settings - automation
Downloads enabled

watchdir/blackhole Enabled
Folder to Watch c:\watchdir

- Downloader
put in a location eg. c:\downloads\premiumizer


should get you started, I dont use plex however but kodi, in sonarr - settings - connect you can notify plex on download that there is a new file etc

**Comment by ash718** [comment]
he " C:\watchdir"  can be any drive letter and with any folder name? or it must be C:\watchdir? i have it setup as J:\ finished downloads\

**Comment by neox387** [comment]
Watchdir is not a finished Download folder tough but you can take whatever you want.

**Comment by ash718** [comment]
ok so can you explain what it is because im very confused. is there a video out there with someone explaining everything?
