### ISSUE TITLE
OMV 5 Docker on PI4

### ISSUE THREAD

**Issue by starhopper1** [piejanssens/premiumizer#255]
Hi, i just startet with docker and linux so please don´t burn me if this is a dumb..^^

I tried to setup everything in portainer but get always
standard_init_linux.go:211: exec user process caused "exec format error"

did anyone got it working on OMV 5 with a Pi and mind sharing there docker stack?

**Comment by tuefekci** [comment]
i did not really test it but atleast for me on an odroid xu4 i need to manually build the docker image so it uses the arm sources.
