### ISSUE TITLE
Settings doesn't survive docker container restart

### ISSUE THREAD

**Issue by nihilist77** [piejanssens/premiumizer#258]
Right now my docker run command looks like this,

```
docker run \
  -d \
  --name=premiumizer \
  -e PUID=1024 \
  -e PGID=100 \
  -e TZ=Europe/London \
  -p 5656:5000 \
  -v /docker/premiumizer/config:/premiumizer/conf \
  -v /docker/downloads/blackhole/torrents:/blackhole \
  -v /docker/downloads/blackhole/downloads:/downloads \
  --restart unless-stopped \
  piejanssens/premiumizer:latest
```

If I restart the container, then the homepage shows "Downloads are disabled". The log says  And the following settings are gone,

- Premiumize.me tab: API key (gone)
- Automation tab: Downloads enabled: OFF (before restart it was ON)
- Automation tab: Watchdir / Blackhole section: Folder to Watch: empty (before restart it was /blackhole)
- Downloader tab: General: Download Location: empty (before restart it was /downloads)

After providing the API key, enabling Downloads and providing blackhole folder, the log says,

```
05-29 03:38:08: ERROR : Downloads disabled because download location is empty
```

Then after setting the "Download Location" everything goes back to normal. I made sure the folders are readable. It seems all the files are getting updated except the `settings.cfg` file.

```
root@lab:~/home# ls -l /docker/premiumizer/config/
total 208
-rwxr-xr-x+ 1 admin users 208896 May 28 12:10 database.db
drwxr-xr-x+ 1 admin users     70 Apr 17 23:05 logs
-rwxrwxrwx  1 admin users   1769 May 25 23:43 settings.cfg
```

**Comment by evopix** [comment]
It looks like this is due to a change made a few days ago, see https://github.com/piejanssens/premiumizer/commit/fdd8c07e0a077f7aca7a3b9b07f1872d63478b0a

The mount point for config files is now `/conf` instead of `/premiumizer/conf`.

**Comment by nihilist77** [comment]
Yup, changing the mountpoint solved the issue. The README needs to be updated.

**Comment by piejanssens** [comment]
I've updated the readme. Thanks.
