### ISSUE TITLE
amd64 docker build fails

### ISSUE THREAD

**Issue by piejanssens** [piejanssens/premiumizer#260]
```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address 'xxx' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
Executing post_checkout hook...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 9 100 9 0 0 37 0 --:--:-- --:--:-- --:--:-- 37
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
post_checkout hook failed! (2)
```

@alinefr

**Comment by alinefr** [comment]
@piejanssens, can you double check this line in [hub.docker.com](https://hub.docker.com/repository/docker/piejanssens/premiumizer/builds/edit)?
<img width="1144" alt="Screenshot 2020-06-03 at 16 21 48" src="https://user-images.githubusercontent.com/4754654/83679821-67a94980-a5b6-11ea-99ab-10400825f12c.png">

Dockerfile location should be just `Dockerfile`, without any extension.

**Comment by piejanssens** [comment]
I had `/` as root path in there. Cheers.
