### ISSUE TITLE
Downloading list has unremovable entries for every percentage of a file download

### ISSUE THREAD

**Issue by leethax666** [piejanssens/premiumizer#265]
It happened on my old system and I did a complete fresh reinstall. I've tried deleted some with no success but I haven't tried all 100. 

I'm using LibreElec 9.2.3 on RasPi4, both fully updated. Screenshot attached.

![screenshot000](https://user-images.githubusercontent.com/1305475/86979232-4ff25180-c170-11ea-8a75-3c26f08f8061.png)

**Comment by piejanssens** [comment]
I think you are looking for this: https://github.com/aenemapy/aenemapyrepo/tree/master/plugin.video.premiumizer
