### ISSUE TITLE
Download jobs duplicated/triplicated

### ISSUE THREAD

**Issue by stuball2** [piejanssens/premiumizer#266]
Hey,

Great job on this project. I have an issue where a single snatch from medusa will result in multiple downloads of the same file showing on the homepage, most of the time 2, occasionally 3... Checking the logs shows:

`07-13 18:28:00: INFO : New watchdir file detected: /media/external/blackhole/tv/[episode].NF.WEBRip.DDP5.1.x264-NTb.nzb`

`07-13 18:28:15: INFO : Added: [episode].NF.WEBRip.DDP5.1.x264-NTb -- Category:  -- Type: NZB -- id: t2B8Dec-0G48rJ6TeGgh7Q`

`07-13 18:28:15: INFO : Added: [episode].NF.WEBRip.DDP5.1.x264-NTb -- Category:  -- Type: NZB -- id: 8L_7Rm0hdEfhuIbxhylOoA`

`07-13 18:28:18: INFO : Added: [episode].NF.WEBRip.DDP5.1.x264-NTb -- Category: tv -- Type: NZB -- id: krsqMnpDUQwqphkFipzMkQ`

This results in 3 entries on the homepage, One with a category of TV, and 2 with no category. 2 of the 3 will show 'Cloud: Error' and one will complete - not usually the one categorised as TV. If I go ahead and delete the the two in error state and change the one that appears successful to the TV category everything continues hunky dory.

I should note that this only appears to happen on a backlog search for 5+ episodes at a time, and I can replicate it. Nothing has changed (because I only set it up yesterday ;p). /media/external is a usb hdd.

**Comment by rkershenbaum** [comment]
When Premiumizer receives "Cloud Error" and retries the download, the category seems to revert to the default category.  That results in the download appearing in the wrong folder.  It happens on my system with a single-episode search.  I reported this in ticket #267 .  If I manually change the category in the Premiumizer UI, a new download is initiated and goes to the correct folder, but the download remains in the default folder and has to be cleaned up manually.
