### ISSUE TITLE
torrent error 

### ISSUE THREAD

**Issue by xxcriticxx** [piejanssens/premiumizer#270]
getting this error on couple of my torrents 

https://pastebin.com/N0gFrgJV

**Comment by xxcriticxx** [comment]
have to add that torrents are 100% done downloading and won't clear from the download section

![Capture](https://user-images.githubusercontent.com/15007183/99875688-782e9a00-2bbf-11eb-9c17-f02d7a574d88.PNG)

**Comment by xxcriticxx** [comment]
also looks like its redownloading each file and eating point away 

![Capture](https://user-images.githubusercontent.com/15007183/99875824-816c3680-2bc0-11eb-88f3-1e5cd16babdc.PNG)

**Comment by 03184** [comment]
+1 to this, Today it maxed out my fair use limit in 1 day !!!!

**Comment by piejanssens** [comment]
@neox387 Any idea what might be wrong here?

**Comment by neox387** [comment]
no idea at 100% pysmartdl is going to merge the parts .00x when its complete maybe you have sonarr ninja it away before premiumizer finishes ?

I use nzbtomedia that watchfolder option in sonarr was supposed to be deprecated and never worked well for me.

so test to some other folder not connected to sonarr to see if you do not have this problem then ?
