### ISSUE TITLE
Premiumizer ignores custom download folder for a category

### ISSUE THREAD

**Issue by leolobato** [piejanssens/premiumizer#274]
I've configured the download location to `/mnt/video/downloaded` and I can see under Categories that it will used subfolders for each one, accordingly (for example `/mnt/video/downloaded/tv` and `/mnt/video/downloaded/movies`).

But if I create a new category (let's call it `rss`) and set it to a custom folder `/mnt/video2/rss-downloads`, it doesn't matter what I do, it will always show the default location + category as the download folder under Categories (`/mnt/video/downloaded/rss`).

I've even tried shutting down Premiumizer, editing `settings.cfg` manually and it will still show the default location under Categories when I restart it.

Is there any way the download location for a specific category can be overridden?

I'm running under dietpi on a raspberry pi.

Thanks!

**Comment by neox387** [comment]
So guess you fixed it with #275, can close this =D
