### ISSUE TITLE
Bug Download Limit Stuck at 0 bytes/s because of Speed Limit

### ISSUE THREAD

**Issue by snipyx** [piejanssens/premiumizer#281]
Hello,

first of all thank you for your great software.

I'm running it in a Docker environment on openmediavault through portrainer.

Most of the time the download is stuck at 0MB/s even though the available network speed is 6MB/s and the speed limit is set to 3MB/s. Every 10-20 seconds the download speed goes up to 1.5MB/s for a duration of 1 second and returns to 0MB/s.

DEBUG LOG:
`01-06 02:33:49       root                                     : DEBUG    : Thread has downloaded 4.4 MB in 100ms. Limit is 3.0 MB/s. Slowing down...`
`01-06 02:33:51       root                                     : DEBUG    : Thread has downloaded 4.4 MB in 1s555ms. Limit is 768 kB/s. Slowing down...`
`01-06 02:33:56       root                                     : DEBUG    : Thread has downloaded 4.4 MB in 7s373ms. Limit is 512 kB/s. Slowing down...`
`01-06 02:34:18       root                                     : DEBUG    : Thread has downloaded 4.1 MB in 12s474ms. Limit is 236 kB/s. Slowing down...`
`01-06 02:34:35       root                                     : DEBUG    : Thread has downloaded 4.1 MB in 122ms. Limit is 205 kB/s. Slowing down...`
`01-06 02:34:56       root                                     : DEBUG    : Thread has downloaded 4.1 MB in 123ms. Limit is 205 kB/s. Slowing down...`

This is some weird behaviour and might be useful for this issue.

I looked up the corresponding code segment in premiumizer.py line 1257:
`if jobs != 0:
                            downloader.limit_speed(cfg.download_speed / jobs)`

My guess is that you are dividing the download speed by the amount of jobs. I don't know how you define jobs, but if there are too many this is the cause of the bug. 

The exact same issue is replicable on 1 concurrent download and 1 thread.

**Comment by piejanssens** [comment]
@neox387 FYI this is where that logging originates: https://github.com/iTaybb/pySmartDL/blob/b93df794e1e60017c42d9520ac097b6fd38c2e8b/pySmartDL/download.py#L65

**Comment by neox387** [comment]
Testing this with just 1 job and works also getting these messages but thats normal behaviour from pysmartdl
the actual speed is working and it sort of correct in gui ranging from 2.4-3.4 MB/s

> 

01-09 17:28:08       root                                     : DEBUG    : Thread has downloaded 1.1 MB in 103ms. Limit is 1.0 MB/s. Slowing down...
01-09 17:28:09       root                                     : DEBUG    : Thread has downloaded 1.2 MB in 139ms. Limit is 1.0 MB/s. Slowing down...
