### ISSUE TITLE
"Loading Download Tasks" forever

### ISSUE THREAD

**Issue by Daniel15** [piejanssens/premiumizer#284]
When I go to Premiumizer, I just see this spinner forever:

![image](https://user-images.githubusercontent.com/91933/104107570-01825480-5272-11eb-8e3d-fb551e3d7bf8.png)

It looks like the socket.io connection doesn't properly handle the base path so for example if I use `/prem/` it'll still try to hit `/socket.io/` rather than `/prem/socket.io/`.

**Comment by neox387** [comment]
Mm, more reports with spinning wheels

Do you use a reverse proxy to ?

Did you fill this in under settings - global:
Enter custom host and/or domain to protect against CORS vulnerability

**Comment by Daniel15** [comment]
> Do you use a reverse proxy to ?

Yeah

> Did you fill this in under settings - global:
> Enter custom host and/or domain to protect against CORS vulnerability

Yes, I filled this in.


I fixed the issue by moving to a subdomain (eg. `prem.example.com`) rather than a subdirectory (eg. `example.com/prem`). It looks like some requests from Premiumizer don't properly handle subdirectories, even when the "Reverse proxy URL base" is filled in.

**Comment by neox387** [comment]
Maybe the reverse proxy config, I had this in the readme but seems its been removed xO

I am using this without a problem so it can work.
xxx.duckdns.org/prem

**Comment by neox387** [comment]
Using the following with nginx, but ye did not actually notice that socket.io is not under /prem/socket.io lol wonder if it's even possible to do this, but anyway it works here like this. 

    location /prem {
        proxy_pass http://internal_ip:8903;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /socket.io {
        proxy_pass http://internal_ip:8903/socket.io;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host host;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
    }

**Comment by Daniel15** [comment]
Yeah, that works, but I'd prefer it to use `/prem/socket.io` in case I want to have something else at `/socket.io`.

**Comment by neox387** [comment]
It is possible looking into it

**Comment by neox387** [comment]
It did work for you before some update? Might be the new flask socket io or engine bump causing this.

Can't get it to work atm on /prem/socket.io

**Comment by Daniel15** [comment]
This is the first time I've used Premiumizer, so I'm not sure if this worked previously.

**Comment by neox387** [comment]
OK, I'll see when I have more time to get it work on the proxy url base, but at least you got it working using extra subdomain meanwhile :)

**Comment by neox387** [comment]
fixed in #283

**Comment by mohitjoshi155** [comment]
i also face this issue...i dont use any reverse proxy
