### ISSUE TITLE
Concurrent downloads setting for aria2

### ISSUE THREAD

**Issue by Daniel15** [piejanssens/premiumizer#286]
I changed the number of simultaneous downloads to 10, but aria still seems to download one at a time. Does this setting not affect aria?

**Comment by neox387** [comment]
It is only for pysmartdl, the option is under that section ;)

Jdownloader have to set it from the program itself

Aria same it's in the startup command as described under the toggle switch --max-connection-per-server=16

**Comment by Daniel15** [comment]
> the option is under that section ;)

It's not though; it's under the "general" section 😛 

![image](https://user-images.githubusercontent.com/91933/104133589-5b9a1d00-5339-11eb-8d3d-f2fb2ad0b64f.png)

> Aria same it's in the startup command as described under the toggle switch --max-connection-per-server=16

Are you sure Premiumize handles this properly? `max-connections-per-server` and `max-concurrent-downloads` are both set correctly, yet Premiumizer still only seems to send one file to Aria at a time. I watch it in the "ariang" web interface and I just see one file appear at a time.

**Comment by neox387** [comment]
Whoops you're right I read threads :)

The general section is for the apscheduler to hold back jobs, so maybe if aria is not accepting more then 1 it's cause its settings are set like that donno, using jdownloader myself

**Comment by neox387** [comment]
Yea look like more then 1 is causing problems with aria

What I really like about Jdownloader is that it creates a package instead of downloading file per file makes it easier to track the progresss etc :)
