### ISSUE TITLE
Permissions of files created by Docker image

### ISSUE THREAD

**Issue by Spoil001** [piejanssens/premiumizer#289]
I'm running premiumizer using Docker under a 'docker' user and shared group.

New files get created with **read/write** access for the **user** and only **read** access for the **group**.

Every user in the group should be able to move/rename the files.

A solution would be to allow setting a umask - https://wiki.archlinux.org/index.php/Umask

**Comment by jjersto** [comment]
Got exactly the same problem. Other than that, this program is awesome! :)

**Comment by daxxio** [comment]
Got exactly the same problem. Other than that, this program is awesome! :)

**Comment by neox387** [comment]
no idea about docker stuff should be easy for someone to fix with the docker file ?

something like this ?
http://widerin.net/blog/change-umask-in-docker-containers/
