### ISSUE TITLE
Please add axel as alternative downloader.

### ISSUE THREAD

**Issue by sirapm** [piejanssens/premiumizer#291]
Axel works wonderful using https connections to Premiumizer files.
Quite often, I have download jobs getting stuck, restarting over and over again. One largish job, used up all my credits overnight at Premiumizer so I had to buy a topup.
One huge benefit with axel is the ability to resume. You kick it off once. If for one or the other reason it fails, you just resubmit the same job and it will pick up from where it last were and no duplicate downloading.
I'm on linux and docker so I'm not sure if axel is available on windows.
Cheers
M

**Comment by neox387** [comment]
from what I can find I do not see axel supporting a way to interact with it from a remote port like aria2s RPC 

aria2 should be very similar or even better ?
there is however still a problem if you try to use more then 1 download at the same time #286
