### ISSUE TITLE
Outdated Docker image for arm32v7 - 2020/06/03

### ISSUE THREAD

**Issue by Spoil001** [piejanssens/premiumizer#304]
The docker image for arm32v7 is very old and it still is getting pulled using latest.

`arm32v7 | c2e4ee84670e | 108.25 MB | 2020/06/03 15:44:58`

**Comment by piejanssens** [comment]
Anyone willing to chip in? @alinefr @danielfiniki

**Comment by Spoil001** [comment]
If you can't reproduce, it's probably an issue with my QNAP device.
But arm32v7 was last pushed 10 months ago: https://hub.docker.com/layers/piejanssens/premiumizer/arm32v7/images/sha256-519266b7ed6a930720e1e92260b49466007d2ba302f1188b7e86b49920ff759d?context=explore

**Comment by danielfiniki** [comment]
@Spoil001 The new image should be available now. Could you give it a try to see if it works?

**Comment by Spoil001** [comment]
It's working. Thank you very much.
