### ISSUE TITLE
Doesn't start since updating to Python 3.9

### ISSUE THREAD

**Issue by CarlosHartmann** [piejanssens/premiumizer#316]
It wasn't working for me anymore so I decided to set up a fresh install. Following the macOS install steps, the first not to work is `virtualenv -p /usr/local/bin/python3 envf`

It returns:
`pkg_resources.DistributionNotFound: The 'importlib-resources>=1.0' distribution was not found and is required by virtualenv`

Trying to start premiumizer after installing throws unknown module errors first for apprise, then bencode, then BTL. The last one I couldn't install.

Not sure if this has anything to do with Python 3.9 but that was the timing in my case; first the update to the newest Python, then the issues next time I tried starting premiumizer.

**Comment by CarlosHartmann** [comment]
Python 3.8 works fine so I guess it'll be a matter of time till it works on 3.9. Leaving the issue open till then.

**Comment by hurricane-dorian** [comment]
Works just fine with python 3.9 (tested in Linux)
the virtualenv error message suggests your python environment is screwed up.
Try this thread for possible fixes. [https://stackoverflow.com/questions/60416277/how-do-i-fix-this-error-distributionnotfound-the-zipp-0-5-distribution-was](url)

**Comment by CarlosHartmann** [comment]
> Works just fine with python 3.9 (tested in Linux)
> the virtualenv error message suggests your python environment is screwed up.
> Try this thread for possible fixes. [https://stackoverflow.com/questions/60416277/how-do-i-fix-this-error-distributionnotfound-the-zipp-0-5-distribution-was](url)

Thank you, this worked. Just FYI, you didn't use the url syntax correctly, but it doesn't matter. Important is that the provided thread fixed it!
