### ISSUE TITLE
Premiumizer ignores/loses category

### ISSUE THREAD

**Issue by Pokora22** [piejanssens/premiumizer#320]
Not 100% sure if I'm not doing something wrong. Have premiumizer watchdir set to my torrent dir with all catogories as subfolders in there. When putting a torrent file in, it'll get taken and the files will be loaded onto my premiumize cloud, but premiumizer will not download it - it's always missing the category.
![image](https://user-images.githubusercontent.com/26257634/136112651-cfe55d26-be14-4602-9c7d-a7f0051b36da.png)

I enabled debug and checked that the category seems to be applied:
10-05 23:27:30       root                                     : INFO     : Added: Candyman.2021.2160p.WEB-DL.x265.10bit.HDR.DDP5.1-NOGRP -- Category: movie -- Type: Torrent -- id: QW46xUs86Q8GDycdtsAAjQ

but it soon is overridden:
10-05 23:27:31       root                                     : INFO     : Added: Candyman.2021.2160p.WEB-DL.x265.10bit.HDR.DDP5.1-NOGRP -- Category:  -- Type:  -- id: OYPb12M5yqccRVwZ2zNcTA

Full debug log is here: [https://pastebin.com/4XUgYSfW](https://pastebin.com/4XUgYSfW)

**Comment by cremor** [comment]
A few days ago I started to have the same problem for every Torrent download. It worked fine previously and I didn't change any setting.

**Comment by msheakoski** [comment]
> If they cant fix this or is on purpose will need to check by returned name instead of id :/

@neox387 I do not think that checking the name is enough to associate the transfer and file. If you look at my previous example, the name changes from "rartv" to "rarbg". I see this happening on most torrents.

**Comment by neox387** [comment]
> > If they cant fix this or is on purpose will need to check by returned name instead of id :/
> 
> @neox387 I do not think that checking the name is enough to associate the transfer and file. If you look at my previous example, the name changes from "rartv" to "rarbg". I see this happening on most torrents.

We add the name based on what is in the .torrent file, premiumize.me names it differently based on what it gets from p2p ? We change our task name to be same as API response from transfer/list, this was no problem since the ids remained the same but for unknown reason now they are not, got a standard reply email back that its busy and responds can take longer -_-

**Comment by neox387** [comment]
They are active on twitter it seems.
https://twitter.com/premiumizeme/status/1446371919649853444

**Comment by msheakoski** [comment]
Downloads are working again over here as well (Docker image), no need to manually select a category. @neox387 it is probably safe to revert the changes related to this issue since P.me seems to have fixed the IDs.

**Comment by neox387** [comment]
It's np still use id matching first and name as alternative 😀

**Comment by msheakoski** [comment]
> It's np still use id matching first and name as alternative 😀

True. As a backup method, it makes sense to have in case there are API issues again. Thank you for adding it! ❤️
