### ISSUE TITLE
Premiumizer stopped working two nights ago.

### ISSUE THREAD

**Issue by berenger4079** [piejanssens/premiumizer#324]
I have had premiumizer for the past few months and had no issues.  Two days ago, it stopped pulling magnet links from the folder and when I click on the bookmarked link, it says This site can’t be reached localhost refused to connect. I have reinstalled it twice, tried it on both Chrome and firefox and restart my entire computer, but it is not working. I have also turned off my firewall and it still says the same message.

**Comment by chris-fp** [comment]
Not sure if it's related but my premiumizer has also stopped working and no changes recently made to it.  It is failing on the premiumizer.py script by basicallly saying error at the following lines

import apprise
import bencode
import gevent
import myjdapi
import requests
import six
from apscheduler.schedulers.gevent import GeventScheduler
from chardet import detect
from flask import Flask, flash, request, redirect, url_for, render_template, send_from_directory
from flask_apscheduler import APScheduler
from flask_compress import Compress
from flask_login import LoginManager, login_required, login_user, logout_user, UserMixin
from flask_socketio import SocketIO, emit
from gevent import local
from pySmartDL import SmartDL, utils
from watchdog import events
from watchdog.observers import Observer
from werkzeug.utils import secure_filename

I am looking into it at the moment and will add additional comments if I find anything

**Comment by chris-fp** [comment]
I re-did the manual steps (for Windows) and it has repaired it.  I have just remembered that the most recent WIndows big update was installed, perhaps something in that caused the issue?

**Comment by berenger4079** [comment]
When I do it manually, it says 
C:\Users\beren>git clone https://github.com/piejanssens/premiumizer.git C:\Premiumizer
fatal: destination path 'C:\Premiumizer' already exists and is not an empty directory.

C:\Users\beren>python -m pip install --upgrade pip
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\Users\beren>python -m pip install -r c:\Premiumizer\requirements.txt
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\Users\beren>python C:\Premiumizer\premiumizer\premiumizer.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I have already manually installed python today so I am not sure what to do.  I usually don't work at this level.

**Comment by neox387** [comment]
If you uninstall premiumizer python and git, and then use the installer again it should also work

**Comment by berenger4079** [comment]
Perfect, that fixed it.
