### ISSUE TITLE
Clean install does not work - Windows 10

### ISSUE THREAD

**Issue by chris-fp** [piejanssens/premiumizer#325]
I've had to rebuild my server where I have plex, sonarr, radarr etc.etc. running and the only thing that doesn't work is Premiumizer.  When I first installed premiumizer months ago, pretty sure it was version 1.0 and it worked ok.

I have just done a clean windows install (win 10 21H1 19043.1348) and followed the manual instructions - Github 2.34.0 64bit followed by Python 3.10.0.amd64 bit and then the manual instructions when I run the command "C:\Premiumizer\premiumizer\premiumizer.py" I get the following:-

C:\WINDOWS\system32>python C:\Premiumizer\premiumizer\premiumizer.py
Traceback (most recent call last):
  File "C:\Premiumizer\premiumizer\premiumizer.py", line 36, in <module>
    from flask_compress import Compress
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_compress\__init__.py", line 1, in <module>
    from .flask_compress import Compress
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_compress\flask_compress.py", line 14, in <module>
    import brotli
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

I've added a text file which shows what I did - hopefully somebody can explain what's going on.

**Comment by chris-fp** [comment]
[premiumizer issue.txt](https://github.com/piejanssens/premiumizer/files/7550028/premiumizer.issue.txt)

**Comment by neox387** [comment]
Try with python 3.9.x
Some packages are not ready for 3.10

https://github.com/neox387/PremiumizerInstaller/commit/bcb00996437492e7d3b9e53de10f324a4a8142c6

**Comment by chris-fp** [comment]
I'd just tried it on 3.8 and got the same error. Will try with 3.9

Is it ok to use 64bit version or should it be 32bit ?

**Comment by chris-fp** [comment]
I get the same error :(


C:\WINDOWS\system32>python C:\Premiumizer\premiumizer\premiumizer.py
Traceback (most recent call last):
  File "C:\Premiumizer\premiumizer\premiumizer.py", line 36, in <module>
    from flask_compress import Compress
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_compress\__init__.py", line 1, in <module>
    from .flask_compress import Compress
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_compress\flask_compress.py", line 14, in <module>
    import brotli
  File "C:\Users\chris\AppData\Local\Programs\Python\Python39\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

**Comment by neox387** [comment]
64 is good
I see readme does not mention to do
Python - m pip install pywin32
Not sure if it was only for nzbToMedia or also for other packages maybe that's it. 
I see flask compress produces the error
If you Google brotli it also mention vcredist

https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by chris-fp** [comment]
You must be mind reading me - I'd just found on the web about the vc_redist.  Installed these and it works :D

Obviously I'd prefer Premiumizer to be run as a service but I'd already tried it but it failed but I am thinking that it is perhaps to do with no having vc_redist installed before I run the windows installer?

**Comment by neox387** [comment]
Ok not sure why i removed vcredist from my installer oO need to include it again Thanks =D
https://github.com/neox387/PremiumizerInstaller/commit/74e185d4f4a2553a21853065c51f937a30500978

I use nssm64 to create the service with installer

**Comment by chris-fp** [comment]
> Ok not sure why i removed vcredist from my installer oO need to include it again Thanks =D [neox387/PremiumizerInstaller@74e185d](https://github.com/neox387/PremiumizerInstaller/commit/74e185d4f4a2553a21853065c51f937a30500978)

I'm guessing the first time I installed Premiumizer way back I'd already installed vc-redist for something else :)

> I use nssm64 to create the service with installer

**Comment by chris-fp** [comment]
Just uninstalled python & Git, deleted c:\premiumizer and then installed using Windows installer and all sweet and running 👍

**Comment by neox387** [comment]
I used the inno script from from a sonarr fork back in the day but can't be bothered to spend time trying to fix it so it could use exicting python/git so ye 😄

**Comment by chris-fp** [comment]
might be worth updating the manual instructions and readme to  include Python - m pip install pywin32 command and also that you need to install the vc-redist stuff, especially if a clean install of windows :)
