### ISSUE TITLE
Success! Now, how do I make this run on startup (Ubuntu)

### ISSUE THREAD

**Issue by ferfey** [piejanssens/premiumizer#328]
I've got everything running and its working nicely with Radarr/Sonarr/NZBD etc.
How do I make this program run headless when I start my computer (linux/Ubuntu)?

**Comment by i-am-the-slime** [comment]
I'd like to make a systemd service for this, but I have no clue how to do the crazy python virtualenv 💩 .

**Comment by i-am-the-slime** [comment]
@ferfey 
```
[Unit]
Description=premiumizer download manager
After=multi-user.target

[Service]
User=mark
Type=simple
WorkingDirectory=/home/mark/tools/premiumizer/
Environment=PYTHONPATH=/home/mark/tools/premiumizer/premiumizer
ExecStart=/home/mark/tools/premiumizer/env/bin/python3 premiumizer/premiumizer.py
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

In `/lib/systemd/system/premiumizer.service`

Then `sudo systemctl daemon-reload`

And `sudo systemctl start premiumizer`.
