### ISSUE TITLE
premiumizer stuck on loading tasks

### ISSUE THREAD

**Issue by mohitjoshi155** [piejanssens/premiumizer#333]
logs on debug mode show this

03-14 11:20:40       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
03-14 11:20:40       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2022-03-14 11:20:41.424517+00:00 (in 0.997590 seconds)
03-14 11:20:40       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:41 GMT)" (scheduled at 2022-03-14 11:20:40.424517+00:00)
03-14 11:20:40       root                                     : DEBUG    : def update started
03-14 11:20:40       root                                     : DEBUG    : def prem_connection started
03-14 11:20:40       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
03-14 11:20:40       root                                     : DEBUG    : def parse_task started
03-14 11:20:40       root                                     : DEBUG    : def get_task started
03-14 11:20:40       root                                     : DEBUG    : def get_task started
03-14 11:20:40       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:41 GMT)" raised an exception
Traceback (most recent call last):
  File "/app/premiumizer.py", line 1667, in parse_tasks
    if '% of' in transfer['message']:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/premiumizer.py", line 1616, in update
    idle = parse_tasks(transfers)
  File "/app/premiumizer.py", line 1676, in parse_tasks
    progress = int(round(float(transfer['progress']) * 100))
TypeError: float() argument must be a string or a real number, not 'NoneType'
03-14 11:20:41       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
03-14 11:20:41       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2022-03-14 11:20:42.424517+00:00 (in 0.997520 seconds)
03-14 11:20:41       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:42 GMT)" (scheduled at 2022-03-14 11:20:41.424517+00:00)
03-14 11:20:41       root                                     : DEBUG    : def update started
03-14 11:20:41       root                                     : DEBUG    : def prem_connection started
03-14 11:20:41       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
03-14 11:20:41       root                                     : DEBUG    : def parse_task started
03-14 11:20:41       root                                     : DEBUG    : def get_task started
03-14 11:20:41       root                                     : DEBUG    : def get_task started
03-14 11:20:41       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:42 GMT)" raised an exception
Traceback (most recent call last):
  File "/app/premiumizer.py", line 1667, in parse_tasks
    if '% of' in transfer['message']:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/premiumizer.py", line 1616, in update
    idle = parse_tasks(transfers)
  File "/app/premiumizer.py", line 1676, in parse_tasks
    progress = int(round(float(transfer['progress']) * 100))
TypeError: float() argument must be a string or a real number, not 'NoneType'
03-14 11:20:42       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
03-14 11:20:42       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2022-03-14 11:20:43.424517+00:00 (in 0.997209 seconds)
03-14 11:20:42       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:43 GMT)" (scheduled at 2022-03-14 11:20:42.424517+00:00)
03-14 11:20:42       root                                     : DEBUG    : def update started
03-14 11:20:42       root                                     : DEBUG    : def prem_connection started
03-14 11:20:42       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
03-14 11:20:42       root                                     : DEBUG    : def parse_task started
03-14 11:20:42       root                                     : DEBUG    : def get_task started
03-14 11:20:42       root                                     : DEBUG    : def get_task started
03-14 11:20:42       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:43 GMT)" raised an exception
Traceback (most recent call last):
  File "/app/premiumizer.py", line 1667, in parse_tasks
    if '% of' in transfer['message']:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/premiumizer.py", line 1616, in update
    idle = parse_tasks(transfers)
  File "/app/premiumizer.py", line 1676, in parse_tasks
    progress = int(round(float(transfer['progress']) * 100))
TypeError: float() argument must be a string or a real number, not 'NoneType'
03-14 11:20:43       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
03-14 11:20:43       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2022-03-14 11:20:44.424517+00:00 (in 0.997572 seconds)
03-14 11:20:43       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:44 GMT)" (scheduled at 2022-03-14 11:20:43.424517+00:00)
03-14 11:20:43       root                                     : DEBUG    : def update started
03-14 11:20:43       root                                     : DEBUG    : def prem_connection started
03-14 11:20:43       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
03-14 11:20:43       root                                     : DEBUG    : def parse_task started
03-14 11:20:43       root                                     : DEBUG    : def get_task started
03-14 11:20:43       root                                     : DEBUG    : def get_task started
03-14 11:20:43       apscheduler.executors.default            : ERROR    : Job "update (trigger: interval[0:00:01], next run at: 2022-03-14 11:20:44 GMT)" raised an exception
Traceback (most recent call last):
  File "/app/premiumizer.py", line 1667, in parse_tasks
    if '% of' in transfer['message']:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/premiumizer.py", line 1616, in update
    idle = parse_tasks(transfers)
  File "/app/premiumizer.py", line 1676, in parse_tasks
    progress = int(round(float(transfer['progress']) * 100))
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by neox387** [comment]
transfer['message'] non type
Premiumize.me api responds problem.
Some weird transfer in premiumize.me? 

Had it worked for you or new?

I see you use python 3.10 did not try again had to revert to 3.9 for some packages befor.

**Comment by mohitjoshi155** [comment]
ya its started this...since one transfer failed

**Comment by neox387** [comment]
Stop premiumzer and delete the database files

**Comment by mohitjoshi155** [comment]
ya i deleted databse.db 
restarted from inside the app
restarted container....still it keeps on loading

if i remove premiumize api and save it stops but when i enter again same thg starts

**Comment by Kille250** [comment]
Would be nice if the docker image get updated too

**Comment by piejanssens** [comment]
It is, just need to have a bit more patience: https://hub.docker.com/layers/piejanssens/premiumizer/latest/images/sha256-28a09f60d9db78a806421df1ecc9794764d9a29f79edbaa4175664cd4c269588?context=repo

**Comment by Kille250** [comment]
Yea, sorry. But thank you for the fast fix!
