### ISSUE TITLE
Windows 10 - Premiumizer Works for a few days then stops

### ISSUE THREAD

**Issue by coolguysa83** [piejanssens/premiumizer#341]
Hi Everyone!  I've probably had this happen a few times already in the last couple of months of using Premiumizer.  I install it with no problems and it works great for about 3 weeks typically, then the Premiumizer Service starts messing up and the Status changes from Starting, to Running, then Pause and just keeps cycling through that loop.  The only way I've been able to fix it in the past is uninstalling Premiumizer, Git, and Python and then reinstalling them all over again.  Unfortunately this is time consuming to have do this so often and then to have to setup all the paths and everything else in Premiumizer once I get it running again.  Anybody have any suggestions of things I can try or look at to see if I can prevent this from happening in the future or fix my issue now as I ran into again this morning where out of the blue it decided it wanted to act up again?  It just seems so odd that it works fine for about three weeks then just one day it doesn't anymore and to keep having that cycle repeat itself.   Thank you all so much for your time.

**Comment by neox387** [comment]
Have a look at the log file for an issue C:\Premiumizer\premiumizer\conf\logs\premiumizer.log
It is also possible to enable a log for the windows service using cmd: C:\Premiumizer\Installer\nssm.exe edit premiumizer under i/o  error pointing to a text file 
![image](https://user-images.githubusercontent.com/6033262/177042454-89e1e6ee-c7d3-42f2-b2cc-10b757c8cc7c.png)
