### ISSUE TITLE
Blackhole error prevents other files from being processed

### ISSUE THREAD

**Issue by hieronymu** [piejanssens/premiumizer#342]
`06-22 20:43:15: ERROR : Upload of magnet: magnet:?xt=[magnet-details-here] failed, message: You already added this job.`

After i get the above error, premiumizer stops adding any further down load jobs to the queue. I have to delete the file from the blackhole directory, enable interval based automation, and restart to process any other files.

**Comment by neox387** [comment]
found an issue the torrent file should be removed automatically if its already added

**Comment by DevX94** [comment]
I have the same issue. Premiuimizer won't delete the torrent file, so it keeps getting an error. Also categories won't be automatically added to the job most of the times.

**Comment by neox387** [comment]
Did you update and tried again after commit from yesterday? Need to see the error then

**Comment by DevX94** [comment]
I just updated my docker container. When the error comes back I'll post it. Thank you!
