### ISSUE TITLE
"You already added this job"

### ISSUE THREAD

**Issue by sirapm** [piejanssens/premiumizer#347]
Occationally, I see in the log file ERROR: Upload of magnet. with the tailing info announce failed, message: You already added this job. The file stays in the watch folder and ever know and then blocks new  magnes from being uploaded. 
I suggest modify the script to delete the file, if it alreayd exist as a job.
Cheers

**Comment by neox387** [comment]
fforgot this on #344 only did for torrents there. Premiumize.me changed the api message somewhere -_-
