### ISSUE TITLE
Premiumizer stopped working all of sudden with Jdownloader (after latest update?) 

### ISSUE THREAD

**Issue by echophex** [piejanssens/premiumizer#351]
Everything was working flawlessly for months. Now, everything works up until its time for Jdownloader to grab links and actually download. Nothing happens and eventually Premiumizer will show following error:
Failed: download retrying soon

Jdownloader updated to latest. Premiumizer updated to latest. 
I renewed a fresh API in Premiumize.me...no difference. Files are successfully being added to premiumize.me
In Jdownloader settings -- general -- Remove finished downloads is set to never.

Debug log stating:
 Nothing to download / link already exists ? for : Vengeance.2022.1080p.WEBRip.x264
also: Could not find package in JD for: Vengeance.2022.1080p.WEBRip.x264

Did the JD connection perhaps get damaged in the recent update?
Again was working flawlessly for 6+ months, on hundreds of torrents up until a week ago perhaps...

**Comment by neox387** [comment]
Much changed to jdownloader handeling to support files being downloaded in folders.

Here everything still works must be something specific, you have many finished downloads sitting in jdownloader? Because of Jdownloader settings -- general -- Remove finished downloads is set to never.?

Normaly we remove the package after it's finished, my jdownloader is always empty?

**Comment by echophex** [comment]
@neox387 Actually even though I have it set to never clear finished downloads (in jdownloader) it usually always does anyways...at least stuff sent from premiumizer. Therefore I have nothing sitting in Jdownloader. That is my problem...nothing is being picked up to download in Jdownloader from Premiumizer.

**Comment by echophex** [comment]
It truly is like Premiumizer is not communicating with JDownloader...specifically the linkgrabber

**Comment by echophex** [comment]
everything is working fine with the built in Pyloader so its definitely Jdownloader specific.

**Comment by neox387** [comment]
Difficult to find out why it happens tough, you have it for all downloads or they all with multiple folders or single folders / same categories..

Here it works had 2 more downloads today :/

If you can try revert to old version it works again?

Ill see of I can find something but hard when I can't reproduce, would need to debug stop in pycharm on Nothing to download / link already exists to see why there are no files to download,  the next error Could not find package in JD for: should ideal not even go that far if Nothing is send to jd

**Comment by echophex** [comment]
@neox387 Yes, all downloads. And all downloads are in single folders across two categories.
JD is working fine with single folder downloads other than with premiumizer. All being picked up by linkgrabber.
I did an uninstall and reinstall of premiumizer with no luck.
I will try old version just to see if it starts working again. Good idea.

**Comment by neox387** [comment]
installed a fresh windows 11 in a vm installed jdownloader 2 and premiumizerinstaller, used same account for jdownloader with new device, everything works as expected :/

**Comment by neox387** [comment]
I have just encountered this issue with a finished download sitting in jdownloader fixed
