### ISSUE TITLE
.NZB Usenet Support

### ISSUE THREAD

**Issue by PremiumizeNZB** [piejanssens/premiumizer#37]
https://blog.premiumize.me/usenet-cloud-downloader/
Premiumize just introduced the ability to add .nzb files.

Can't contribute to the code myself, so just see this as an enhancement suggestion.

**Comment by neox387** [comment]
Could maybe add this later when it's more stable, just tested a nzb & went straight to error ..

It's nice but not as useful since nzb's start right away at a somewhat decent speed anyway.

**Comment by PremiumizeNZB** [comment]
> It's nice but not as useful since nzb's start right away at a somewhat decent speed anyway.
What do you mean by that? I'm using Premiumizer in combination with Sonarr and Plex for full media automation, so I seem to have another use-case. If Premiumizer gets NZB Support, I'll be able to throw away NZBGet and have one tool less.

**Comment by neox387** [comment]
You are right in not needing nzbget then ye, I just ment that probably you will have to wait first on the cloud download before your download starts.

Anyway I'll look into it

**Comment by neox387** [comment]
Implemented nzb support in #41

but beware, downloading a nzb file might be best to use the categories - extension option to filter out & only download mkv,mp4,srt for example.

in the premiumize.me browser it would display the mkv & a sfv file but when pulling the directory trough the api it started downloading the mkv but allso the .rar parts as nzb's come in.

so premiumize.me seems to unpack those allready & hide's the rar's on there website's directory browser..

**Comment by PremiumizeNZB** [comment]
Thank you very much for the fast implementation, however I found three issues:
1) When DL (from Premiumize to me) is started it stays at 0% progress (Speed: ETA: empty) even though the file gets downloaded successfully in the background. As a result the automatic deletion after downloading doesn't work.
2) When I press "Stop DL" on a NZB file, there is no resume button
3) On Premiumize all the Cloud files are sorted chronologically. However on Premiumizer all the NZB files get added to the buttom, not the top.

Nothing groundbreaking, I already deleted NZBGet because issue 1) doesn't cause any issues with Sonarr/Plex, I just have to manually delete the torrents.

**Comment by neox387** [comment]
1) fixt in next PR , is a bug caused by premiumize.me.
there is however few information for nzb's ---> premiumize.me cloud: no info on speed / eta / size, just a percentage bar.

2) this is normal, there is only a stop button no pause/resume, that is because there are issues with the resume functionality and this is external code can't easy fix it.

so when u stop few sec later the category will be gone & the download will go to waiting for category, at that time u can reselect the category you want & it will queue up the download again.

3) this is a bit more difficult, will look into it

**Comment by PremiumizeNZB** [comment]
1) is fully fixed now, thank you very much. My Speed: Eta: Empty comment was meant for the DL from Premiumize to me, not to the Premiumize Cloud itself. 
2) Thanks for the information, didn't realize that the category gets reseted after stopping the download.

I'll close the issue now.
