### ISSUE TITLE
Service not starting since commit 05e8865

### ISSUE THREAD

**Issue by PremiumizeNZB** [piejanssens/premiumizer#38]
I'll keep this brief because I couldn't find any useful log information:
Ever since commit 05e8865 "code cleanup" the service simply can't start anymore and throws an "cannot start" error if I try to do so manually via services.msc. Both manual or in-browser-upgrade doesn't work.

Operating System: Windows 10 Pro 64bit
Tried on two machines, Service is logged in to an administrator account.

The newest cloned repository works just fine when I replace the Premiumizer.py with Version 0fb481e or older.
Let me know if you need additional troubleshoot information.

**Comment by piejanssens** [comment]
@neox387 Can you have a look mate?

**Comment by neox387** [comment]
Only reason this could be is because you don't have the myjdapi package.

uninstall from the installer folder, and reinstall again.

this will install the requirements etc automatically, I have updated the python & git version for the installer (still same installer no newer version needed)

**Comment by PremiumizeNZB** [comment]
I've ran the installer multiple times, but never paid close attention to what the command windows said.
Here is the tiny little detail which solved everything:

> error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

This line was hard to find because everything moves so fast in the command windows (I think it was the third one popping up), so I had to take  screenshots to even read it.

Installed it from http://aka.ms/vcpython27, ran the installer again. Now everything works perfectly.

Any mention of Visual C++ 9.0 is completely missing from the README.md, so would be nice for other if you could add this crucial requirement.

**Comment by neox387** [comment]
Mm did not notice this, probably pywin installation needs this.

I'll add it to the readme and try to get this into the installer ... Another 83mb dependency, damn u windows xD

**Comment by neox387** [comment]
Installer is updated, included visual c++ & enabled a logfile :)

PR open to add Visual c++ to the readme

**Comment by PremiumizeNZB** [comment]
Thanks, I'll close the issue now.
