### ISSUE TITLE
Libs: Gevent - Flask-socketio

### ISSUE THREAD

**Issue by neox387** [piejanssens/premiumizer#4]
Would be nice to update to latest version v2?
https://flask-socketio.readthedocs.org/en/latest/

but dependencies etc have changed
python-socketio/engineio instead of gevent-socketio

I've tried this but doesn't work.

Allso to remove gevent this needs to change i think:
from apscheduler.schedulers.gevent import GeventScheduler

geventscheduler requires gevent package to be installed.

**Comment by neox387** [comment]
Ok I fixt it latest flask-socketio working now :)

**Comment by piejanssens** [comment]
I just fixed some things on master, and at the same time I guess I fucked something up unless it was already broken in your previous PR. I' don't have to time figure out why no page is loading (for me at least). The app is running, but I can't access any web page.

I removed the different libs for the watchidr and replaced it by a cross platform solution based on the python lib watchdog. I also fixed creation of the settings.cfg, storing the torrent hash from torrents in the watchdir (lib bencode) so we can keep track of the category and we are now able to determine the download category based on the dir the torrent is placed inside the watchdir. So ../watchdir/tv/somefile.torrent will be cached as category 'tv'.

**Comment by neox387** [comment]
I'll check it out, didn't have pages not loading yet.

**Comment by piejanssens** [comment]
If we get that fixed again we're very close to having premiumizer work in the full process with SR/CP/Sonar/... > premiumizer > nzbToMedia :wink:

**Comment by neox387** [comment]
Well the problem was that when debug enabled, flask uses werkzeug instead of gevent and werkzeug uses watchdog when detected, so when u added watchdog the reloader got changed but this conflicts with gevent,
I changed this to use the default stat reloader instead of watchdog, but this acctualy doesn't seem to 'catch' the debugging seems something like: https://github.com/aldanor/SocketIO-Flask-Debug tries to do it but this is old & uses gevent-socketio while now we are on python-socketio

I'll look more into it tomorrow u can test: 
https://github.com/neox387/premiumizer/tree/dev

**Comment by piejanssens** [comment]
I guess this describes the exact problem? https://github.com/gorakhargosh/watchdog/issues/306
Where are we using Gevent currently?

**Comment by neox387** [comment]
Allready have all the latest github versions but no go :)

& no not get rid of flask socketio, we just had a very old version 0.x while now i'm at 2.1 just the dependencies changed: https://flask-socketio.readthedocs.org/en/latest/

flask socketio uses in order if found: eventlet, gevent,werkzeug, but for debug mode it's allways werkzeug. but apparently it's not recommended to keep running werkzeug for non debugging, so when pip install gevent it will use that & we need to install gevent for:
from apscheduler.schedulers.gevent import GeventScheduler
scheduler = APScheduler(GeventScheduler())

unless u can change donno :D 


I tried with eventlet but not working atm as it's stuck on loading download tasks so something in the socket stuff is not working.

Anyway it is working now just in debug mode flask does not show the debug output for werkzeug

**Comment by neox387** [comment]
the category of the watchdir map is not working tough, checking it:
File "C:\premiumizer\Premiumizer.py", line 365, in process
    torrent_file = open(sys.argv[1], "rb")
IndexError: list index out of range

**Comment by piejanssens** [comment]
My bad. Should be "torrent_file = event.src_path"

**Comment by neox387** [comment]
Ok changed, next problem:
File "C:\premiumizer\Premiumizer.py", line 313, in add_task
    tasks.append(DownloadTask(0,0,hash,'','upload',category))
TypeError: __init__() takes exactly 6 arguments (7 given)

**Comment by piejanssens** [comment]
Weird, maybe use None instead of '' for adding the task without a name?

**Comment by piejanssens** [comment]
@neox387 tried None? 
btw can we get in touch to discuss things more easily? send me a DM on Twitter @piejanssens

**Comment by neox387** [comment]
send u a tweet I think lol not using twitter much.

tasks.append(DownloadTask(0,0,hash,None,'upload',category))
TypeError: __init__() takes exactly 6 arguments (7 given)

I don't see 7 arguments ? :/

**Comment by piejanssens** [comment]
Ik heb je een DM gestuurd op twitter.
