### ISSUE TITLE
Internal Downloader

### ISSUE THREAD

**Issue by neox387** [piejanssens/premiumizer#43]
pySmartDL issues:
1. [error](https://github.com/neox387/pySmartDL/blob/master/pySmartDL/pySmartDL.py#L690) on this like pause/resume etc..
2. downloading in chunks saves the chunks separately to the hard disk & then has to combine everything at the end
3. pysmartdl using urllib2 instead of requests ?

I have not found another python downloader with the same functions, maybe pyload when 0.5 is released ..

**Comment by neox387** [comment]
After more testing I would advise to use Jdownloader instead, to much randomness with pysmartdl failing in a read error & weird premiumize speeds on a single connection?

pc1:
Chrome & pysmart downloader around 20MB/s
IE 8MB/s
Jdownloader 10 chunks 23 MB/s

pc2:
chrome & IE & pysmartdl around 2-3 MB/s
Jdownloader 10 chunks: 23 MB/s

**Comment by Farthen** [comment]
Being unsatisfied with the stability of pySmartDL I put something together in the last few days...

I'm not really sure it is adequate or good enough, but it seems to work fine for now. I based it on pycurl and it supports aborting/resuming a transfer by storing a json config file next to the download file (which stores download progress and is deleted on successful download)

You can find it at https://github.com/Farthen/pystreamdl. It's not heavily complicated, basically just a wrapper around pycurl. I implemented it using threads, I might switch to gevents though, not sure yet. It doesn't have multi-chunks support yet but it would be possible to have that feature too if desired.

I forked premiumizer and hacked in support for it at https://github.com/Farthen/premiumizer. It's far from perfect right now but seems to work fine at first glance.

I would appreciate any comments :)

**Comment by neox387** [comment]
Development of pysmartdl has resumed by original author it seems so maybe it will get better :) still using Jdownloader myself

**Comment by neox387** [comment]
Well not much good changed on the PysmartDl front..

My biggest problem is multi chunck downloading is not saving in 1 file, meaning it has to write a new file at the end from all the parts that's much useless disk activity + very slow/filling up a network connection.

there should be a way to do it however with 'queue' I think like [this downloader](https://github.com/DiSiqueira/DSDownload/blob/master/src/DSDownload.py)
But to make a complete package to integrate into premiumizer with all the functions would much work.

and without multiple chunks the speed of the download isn't always that good.

That's why I'm using Jdownloader 2 :), so I'm not sure on how 'stable' PysmartDL is for daily use, would need more feedback/testing for replacing it with for example @farthen pystreamdl =D

**Comment by piejanssens** [comment]
@neox387 
I'm thinking of removing pysmartdl completely and instead offload any local download task to pyload.
Given pyload has the api to allow us to add new tasks and specify the extract/download location.

Thoughts?

**Comment by neox387** [comment]
Just tried pyLoad, seems pretty bad even with multiple connection very slow speed.

Aria2 with webui working better, used a compiled windows package.

BUT
If we remove pysmartdl there is no internal downloader... then the user needs to install Jdownloader or aria2..

Have not looked yet on how to get information about download status from aria2 into python tough..

**Comment by neox387** [comment]
[another webui for aria](https://github.com/mayswind/AriaNg)

**Comment by neox387** [comment]
testing aria2 again, it seems it doesn't have packages like Jdownloader does, bit sad...

Have to add urls 1 by 1 and then keep track on all of them ...

**Comment by neox387** [comment]
Closing this, there is a choise now for external Downloaders as there seems to be no decent python based ones :)
