### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stphnrdmr** [piejanssens/premiumizer#60]
Are you planning on releasing this software under a free license like MIT or GPL?

**Comment by piejanssens** [comment]
I haven't give' it enough thought. Why would you like to know? Any suggestions?

**Comment by stphnrdmr** [comment]
Mostly interested because I just contributed a tiny bit and I'd love that to be licensed freely. MIT is simple, GPL enforces that the software always remains free. [This](http://choosealicense.com/) might help.
