### ISSUE TITLE
Watchdog gets unhandled exception

### ISSUE THREAD

**Issue by nhrjr** [piejanssens/premiumizer#71]
If somehow a filed gets created and deleted, while the MyHandler.process() function is running, an IOError exception gets raised and is not handled inside the watchdog eventhandler.
(In my case, sickrage tries to download a magnet, and then looks for the torrent on torrenproject. Apparently it opens a file, but fails to download. The file gets removed immediately,  leading to the IOError.)

``` File "/opt/premiumizer/virtualenv/lib/python2.7/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
handler.dispatch(event)
File "/opt/premiumizer/virtualenv/lib/python2.7/site-packages/watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
File "/opt/premiumizer/premiumizer.py", line 1166, in on_created
File "/opt/premiumizer/premiumizer.py", line 1136, in process
   hash, name = torrent_metainfo(watchdir_file)
File "/opt/premiumizer/premiumizer.py", line 1191, in torrent_metainfo
    info = metainfo['info']
 IOError: [Errno 2] No such file or directory: 'yyy/xxx.torrent'
```

**Comment by neox387** [comment]
Could set a delay of 10 seconds from the time file gets created to it being used ( and recheck if file exists), should be enough time for sickrage then ? :)

also .magnet files are supported so it's not really needed to 'look' for them ...

**Comment by nhrjr** [comment]
My way to deal with this right now, is to wrap the process() in a try / except block, catching the relevant parts, as I don't want the unhandled exception killing the watchdog, which I think should happen anyway.

For saving magnet files, I agree, but I haven't found a way to do it with sickrage, only sonarr, etc.
As far as I understood, sickrage is checking, if it finds the matching torrent on torrentproject/piratebay to a magnet link it gets from other sites, if they don't provide a torrent file.
