### ISSUE TITLE
Premiumize API authentication not working

### ISSUE THREAD

**Issue by silberistgold** [piejanssens/premiumizer#73]
For the last couple of days premiumizer can not authenticate with the premiumize.me api. To me it looks like they made some undocumented changes that broke the authentication when using a POST with the authentication parameters in body. I can clearly reproduce this when sending a simple POST request to one of the api endpoints from the command line, everything works fine when using a GET and parameters in the url.
Anybody else experiencing the same?

**Comment by neox387** [comment]
yes had this from yesterday also do not see any changes listed on the api ..

**Comment by neox387** [comment]
made a ticket asking premiumize.me ..

**Comment by silberistgold** [comment]
👍

**Comment by piejanssens** [comment]
@neox387 Did you get a reply? Otherwise give me the ticket number and I'll contact the owner directly.

**Comment by neox387** [comment]
No reply yet, and can't see ticket number, however just checked and seems to be working again.

**Comment by piejanssens** [comment]
@silberistgold Working again for you too?

**Comment by neox387** [comment]
just got the reply:

```` 
hI!

this is fixed now, sorry we enabled cross site protection and the first implementation was buggy.

--
Kind regards,

Thomas Pak


CEO
````

**Comment by silberistgold** [comment]
Yes, can confirm that it is working again.
