### ISSUE TITLE
Premiumizer cannot handle failed torrent downloads

### ISSUE THREAD

**Issue by kungfoolfighting** [piejanssens/premiumizer#76]
Hello everyone,
I updated premiumizer today and after the update it was unable to get the list of files in the premiumize.me cloud storage.
I kept getting this message in the logs:
`08-20 14:21:26: ERROR : premiumize.me connection error`
The UI was telling me that i should check my premiumize.me login details.
So I turned on debugging and looked at the code to see what was happening.
As it turns out the code looks at the message it (successfully) retrieves from premiumize.me in line 907 of premiumizer.py and then checks to see if it contains the string '"status":"error"' and if so, it assumes that the connection failed.
Now as it turns out this string did occur in the message for every failed download in my cloud storage. 
So whenever a torrent download failed in premiumize.me, i would not be able to look at the list of available cloud downloads.
I assume that this is a bug.
I am now working around this problem by removing all failed downloads from the cloud downloader.

Best regards!

**Comment by neox387** [comment]
I see, need to fix this status: error is to vague.

But I never had a cloud torrent that failed downloading, could u link me failing torrent to test ? =D

**Comment by kungfoolfighting** [comment]
It might not be very quick to get them to fail. I think they have to not successfully download for 6 or 7 days or something like that.
Since I deleted all the failed downloads I only remember that one of them was the Arthur C Clarke Audiobook collection and i googled for it and found this link: magnet:?xt=urn:btih:AZ6CYZNQMJJCJMPECWBW7WUWWIYJY7HX&dn=The+Arthur+C+Clarke+Collection&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://zer0day.ch:1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://public.popcorn-tracker.org:6969
That might be the one torrent that didnt load. At least it is having trouble resolving the name right now in premiumize.me after readding it.

**Comment by neox387** [comment]
Ok damn would have to wait days to get the errors :D, do u happen to have the error message that premiumize.me gives after status":"error when this happens, you said:
````
08-20 14:21:26: ERROR : premiumize.me connection error
````
But it doesn't include what error, I recently changed them error lines tough.

**Comment by kungfoolfighting** [comment]
https://pastebin.com/n0VFQuzB
This log contains the following line:

> 08-20 14:28:51       root                                     : DEBUG    : 1
This was added by myself to debug the counter.
You can see the message string contains the arthur c clarke collection and other stuff that failed.

**Comment by neox387** [comment]
Ok fixing it, to bad premiumize.me just says status error instead of download failed

**Comment by kungfoolfighting** [comment]
OK thanks a lot! This tool really was an awesome find for me, great work!

**Comment by neox387** [comment]
this is already fixed can close it ^^
