### ISSUE TITLE
Add an option to download files without cat assignment

### ISSUE THREAD

**Issue by Tscherno** [piejanssens/premiumizer#84]
Currently its only possible to download files from the cloud which have an category assigned. It would be great if every finished download could be automatically downloaded and deleted. Additionally it would be nice to have an Buton in the webinterface "Download all".

**Comment by neox387** [comment]
Premiumizer will always need a category, however could make a 'default' category and download everything as mentioned above.

I don't have much time nowadays trough.

**Comment by neox387** [comment]
PR open for this

On the settings page is now a switch 'Download everything and assign the category 'default':'
so everything you add when this is enabled and does not have a category gets the category default :)

A download everything button isn't needed as when u open the home page all the tasks get refreshed and get there default category assigned or automatically based on idle interval settings

**Comment by Tscherno** [comment]
Thanks mate!
