### ISSUE TITLE
Can't start premiumizer after pr#98

### ISSUE THREAD

**Issue by bjsjr** [piejanssens/premiumizer#99]
After updating premiumizer to to pr #98 I could no longer access it from the browser.  My premiumizer.log was filling up with the following errors:

```
01-02 11:12:49: INFO : Running at /home/openhab/premiumizer
01-02 11:12:49: ERROR : Uncaught exception
Traceback (most recent call last):
  File "/home/openhab/premiumizer/premiumizer.py", line 334, in <module>
    cfg = PremConfig()
  File "/home/openhab/premiumizer/premiumizer.py", line 185, in __init__
    self.check_config()
  File "/home/openhab/premiumizer/premiumizer.py", line 213, in check_config
    self.aria2_enabled = prem_config.getboolean('downloads', 'aria2_enabled')
  File "/usr/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'aria2_enabled' in section: 'downloads'

```

To resolve the problem I had to add the following four lines to my settings.cfg:

```
aria2_enabled = 0
aria2_host = localhost
aria2_port = 6800
aria2_secret = premiumizer
```

My settings.cfg is now out-of-sync with settings.cfg.tpl.  My config_version is 1.7 while the template is 1.8 and my req_version is 6.0 while the template is 6.3.

Sorry about the log display but I can't seem to get the code fence to work today.

**Comment by neox387** [comment]
Well do you update from the settings page? Or is this never working for you ? It does more then just Git pull..

Else You will have problems like this ^^

**Comment by neox387** [comment]
I have only tested The whole update procedures on windows tough..

**Comment by bjsjr** [comment]
I have to use git pull.  Updating from the settings page has never worked for me.  I will try updating from the settings page next time and post a debug log.
